/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SiblingExtended {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface SiblingExtendedBase {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface SiblingRoot {
    }
}
declare global {
    interface HTMLSiblingExtendedElement extends Components.SiblingExtended, HTMLStencilElement {
    }
    var HTMLSiblingExtendedElement: {
        prototype: HTMLSiblingExtendedElement;
        new (): HTMLSiblingExtendedElement;
    };
    interface HTMLSiblingExtendedBaseElement extends Components.SiblingExtendedBase, HTMLStencilElement {
    }
    var HTMLSiblingExtendedBaseElement: {
        prototype: HTMLSiblingExtendedBaseElement;
        new (): HTMLSiblingExtendedBaseElement;
    };
    interface HTMLSiblingRootElement extends Components.SiblingRoot, HTMLStencilElement {
    }
    var HTMLSiblingRootElement: {
        prototype: HTMLSiblingRootElement;
        new (): HTMLSiblingRootElement;
    };
    interface HTMLElementTagNameMap {
        "sibling-extended": HTMLSiblingExtendedElement;
        "sibling-extended-base": HTMLSiblingExtendedBaseElement;
        "sibling-root": HTMLSiblingRootElement;
    }
}
declare namespace LocalJSX {
    interface SiblingExtended {
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface SiblingExtendedBase {
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface SiblingRoot {
    }

    interface SiblingExtendedAttributes {
        "prop1": string;
        "prop2": string;
    }
    interface SiblingExtendedBaseAttributes {
        "prop1": string;
        "prop2": string;
    }

    interface IntrinsicElements {
        "sibling-extended": Omit<SiblingExtended, keyof SiblingExtendedAttributes> & { [K in keyof SiblingExtended & keyof SiblingExtendedAttributes]?: SiblingExtended[K] } & { [K in keyof SiblingExtended & keyof SiblingExtendedAttributes as `attr:${K}`]?: SiblingExtendedAttributes[K] } & { [K in keyof SiblingExtended & keyof SiblingExtendedAttributes as `prop:${K}`]?: SiblingExtended[K] };
        "sibling-extended-base": Omit<SiblingExtendedBase, keyof SiblingExtendedBaseAttributes> & { [K in keyof SiblingExtendedBase & keyof SiblingExtendedBaseAttributes]?: SiblingExtendedBase[K] } & { [K in keyof SiblingExtendedBase & keyof SiblingExtendedBaseAttributes as `attr:${K}`]?: SiblingExtendedBaseAttributes[K] } & { [K in keyof SiblingExtendedBase & keyof SiblingExtendedBaseAttributes as `prop:${K}`]?: SiblingExtendedBase[K] };
        "sibling-root": SiblingRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sibling-extended": LocalJSX.IntrinsicElements["sibling-extended"] & JSXBase.HTMLAttributes<HTMLSiblingExtendedElement>;
            "sibling-extended-base": LocalJSX.IntrinsicElements["sibling-extended-base"] & JSXBase.HTMLAttributes<HTMLSiblingExtendedBaseElement>;
            "sibling-root": LocalJSX.IntrinsicElements["sibling-root"] & JSXBase.HTMLAttributes<HTMLSiblingRootElement>;
        }
    }
}
