/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
import { PlaygroundFile } from "./utils";
import { EditorFilesState } from "./components/stencil-playground-editor/stencil-playground-editor";
import { Diagnostic } from "@stencil/core/compiler/browser";
import { PreviewInput, PreviewResult } from "./components/stencil-playground-preview/stencil-playground-preview";
export { PlaygroundFile } from "./utils";
export { EditorFilesState } from "./components/stencil-playground-editor/stencil-playground-editor";
export { Diagnostic } from "@stencil/core/compiler/browser";
export { PreviewInput, PreviewResult } from "./components/stencil-playground-preview/stencil-playground-preview";
export namespace Components {
    interface StencilPlayground {
        /**
          * The list of files in the playground.
          * @default [   {     name: 'my-component.tsx',     content: `import { Component } from '@stencil/core';  @Component({ tag: 'my-component' }) export class MyComponent {   render() {     return <div>Hello from Stencil!</div>;   } } `,   }, ]
         */
        "files": PlaygroundFile[];
    }
    interface StencilPlaygroundEditor {
        /**
          * @default []
         */
        "diagnostics": Diagnostic[];
        /**
          * @default { files: [], activeFileName: '' }
         */
        "filesState": EditorFilesState;
        /**
          * @default ''
         */
        "jsxTypesDts": string;
    }
    interface StencilPlaygroundPreview {
        /**
          * @default {     files: [],     indexHtml: null,     vdomSignals: false,     signalBacking: false,     globalScriptPath: null,     globalStylePaths: [],   }
         */
        "input": PreviewInput;
    }
}
export interface StencilPlaygroundEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStencilPlaygroundEditorElement;
}
export interface StencilPlaygroundPreviewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStencilPlaygroundPreviewElement;
}
declare global {
    interface HTMLStencilPlaygroundElement extends Components.StencilPlayground, HTMLStencilElement {
    }
    var HTMLStencilPlaygroundElement: {
        prototype: HTMLStencilPlaygroundElement;
        new (): HTMLStencilPlaygroundElement;
    };
    interface HTMLStencilPlaygroundEditorElementEventMap {
        "fileChange": { name: string; content: string };
        "activeFileChange": string;
        "editorReady": void;
    }
    interface HTMLStencilPlaygroundEditorElement extends Components.StencilPlaygroundEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStencilPlaygroundEditorElementEventMap>(type: K, listener: (this: HTMLStencilPlaygroundEditorElement, ev: StencilPlaygroundEditorCustomEvent<HTMLStencilPlaygroundEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStencilPlaygroundEditorElementEventMap>(type: K, listener: (this: HTMLStencilPlaygroundEditorElement, ev: StencilPlaygroundEditorCustomEvent<HTMLStencilPlaygroundEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStencilPlaygroundEditorElement: {
        prototype: HTMLStencilPlaygroundEditorElement;
        new (): HTMLStencilPlaygroundEditorElement;
    };
    interface HTMLStencilPlaygroundPreviewElementEventMap {
        "previewResult": PreviewResult;
    }
    interface HTMLStencilPlaygroundPreviewElement extends Components.StencilPlaygroundPreview, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStencilPlaygroundPreviewElementEventMap>(type: K, listener: (this: HTMLStencilPlaygroundPreviewElement, ev: StencilPlaygroundPreviewCustomEvent<HTMLStencilPlaygroundPreviewElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStencilPlaygroundPreviewElementEventMap>(type: K, listener: (this: HTMLStencilPlaygroundPreviewElement, ev: StencilPlaygroundPreviewCustomEvent<HTMLStencilPlaygroundPreviewElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStencilPlaygroundPreviewElement: {
        prototype: HTMLStencilPlaygroundPreviewElement;
        new (): HTMLStencilPlaygroundPreviewElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-playground": HTMLStencilPlaygroundElement;
        "stencil-playground-editor": HTMLStencilPlaygroundEditorElement;
        "stencil-playground-preview": HTMLStencilPlaygroundPreviewElement;
    }
}
declare namespace LocalJSX {
    interface StencilPlayground {
        /**
          * The list of files in the playground.
          * @default [   {     name: 'my-component.tsx',     content: `import { Component } from '@stencil/core';  @Component({ tag: 'my-component' }) export class MyComponent {   render() {     return <div>Hello from Stencil!</div>;   } } `,   }, ]
         */
        "files"?: PlaygroundFile[];
    }
    interface StencilPlaygroundEditor {
        /**
          * @default []
         */
        "diagnostics"?: Diagnostic[];
        /**
          * @default { files: [], activeFileName: '' }
         */
        "filesState"?: EditorFilesState;
        /**
          * @default ''
         */
        "jsxTypesDts"?: string;
        "onActiveFileChange"?: (event: StencilPlaygroundEditorCustomEvent<string>) => void;
        "onEditorReady"?: (event: StencilPlaygroundEditorCustomEvent<void>) => void;
        "onFileChange"?: (event: StencilPlaygroundEditorCustomEvent<{ name: string; content: string }>) => void;
    }
    interface StencilPlaygroundPreview {
        /**
          * @default {     files: [],     indexHtml: null,     vdomSignals: false,     signalBacking: false,     globalScriptPath: null,     globalStylePaths: [],   }
         */
        "input"?: PreviewInput;
        "onPreviewResult"?: (event: StencilPlaygroundPreviewCustomEvent<PreviewResult>) => void;
    }

    interface StencilPlaygroundEditorAttributes {
        "jsxTypesDts": string;
    }

    interface IntrinsicElements {
        "stencil-playground": StencilPlayground;
        "stencil-playground-editor": Omit<StencilPlaygroundEditor, keyof StencilPlaygroundEditorAttributes> & { [K in keyof StencilPlaygroundEditor & keyof StencilPlaygroundEditorAttributes]?: StencilPlaygroundEditor[K] } & { [K in keyof StencilPlaygroundEditor & keyof StencilPlaygroundEditorAttributes as `attr:${K}`]?: StencilPlaygroundEditorAttributes[K] } & { [K in keyof StencilPlaygroundEditor & keyof StencilPlaygroundEditorAttributes as `prop:${K}`]?: StencilPlaygroundEditor[K] };
        "stencil-playground-preview": StencilPlaygroundPreview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-playground": LocalJSX.IntrinsicElements["stencil-playground"] & JSXBase.HTMLAttributes<HTMLStencilPlaygroundElement>;
            "stencil-playground-editor": LocalJSX.IntrinsicElements["stencil-playground-editor"] & JSXBase.HTMLAttributes<HTMLStencilPlaygroundEditorElement>;
            "stencil-playground-preview": LocalJSX.IntrinsicElements["stencil-playground-preview"] & JSXBase.HTMLAttributes<HTMLStencilPlaygroundPreviewElement>;
        }
    }
}
