/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
import { PreviewResult } from "./components/stencil-playground-preview/stencil-playground-preview";
export { PreviewResult } from "./components/stencil-playground-preview/stencil-playground-preview";
export namespace Components {
    interface StencilPlayground {
        /**
          * @default `import { Component, h } from '@stencil/core';  @Component({ tag: 'my-component' }) export class MyComponent {   render() {     return <div>Hello from Stencil!</div>;   } } `
         */
        "code": string;
    }
    interface StencilPlaygroundEditor {
        /**
          * @default ''
         */
        "value": string;
    }
    interface StencilPlaygroundPreview {
        /**
          * @default null
         */
        "compiledCode": string | null;
        /**
          * @default null
         */
        "componentTag": string | null;
    }
}
export interface StencilPlaygroundEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStencilPlaygroundEditorElement;
}
export interface StencilPlaygroundPreviewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStencilPlaygroundPreviewElement;
}
declare global {
    interface HTMLStencilPlaygroundElement extends Components.StencilPlayground, HTMLStencilElement {
    }
    var HTMLStencilPlaygroundElement: {
        prototype: HTMLStencilPlaygroundElement;
        new (): HTMLStencilPlaygroundElement;
    };
    interface HTMLStencilPlaygroundEditorElementEventMap {
        "valueChange": string;
    }
    interface HTMLStencilPlaygroundEditorElement extends Components.StencilPlaygroundEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStencilPlaygroundEditorElementEventMap>(type: K, listener: (this: HTMLStencilPlaygroundEditorElement, ev: StencilPlaygroundEditorCustomEvent<HTMLStencilPlaygroundEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStencilPlaygroundEditorElementEventMap>(type: K, listener: (this: HTMLStencilPlaygroundEditorElement, ev: StencilPlaygroundEditorCustomEvent<HTMLStencilPlaygroundEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStencilPlaygroundEditorElement: {
        prototype: HTMLStencilPlaygroundEditorElement;
        new (): HTMLStencilPlaygroundEditorElement;
    };
    interface HTMLStencilPlaygroundPreviewElementEventMap {
        "previewResult": PreviewResult;
    }
    interface HTMLStencilPlaygroundPreviewElement extends Components.StencilPlaygroundPreview, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStencilPlaygroundPreviewElementEventMap>(type: K, listener: (this: HTMLStencilPlaygroundPreviewElement, ev: StencilPlaygroundPreviewCustomEvent<HTMLStencilPlaygroundPreviewElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStencilPlaygroundPreviewElementEventMap>(type: K, listener: (this: HTMLStencilPlaygroundPreviewElement, ev: StencilPlaygroundPreviewCustomEvent<HTMLStencilPlaygroundPreviewElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStencilPlaygroundPreviewElement: {
        prototype: HTMLStencilPlaygroundPreviewElement;
        new (): HTMLStencilPlaygroundPreviewElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-playground": HTMLStencilPlaygroundElement;
        "stencil-playground-editor": HTMLStencilPlaygroundEditorElement;
        "stencil-playground-preview": HTMLStencilPlaygroundPreviewElement;
    }
}
declare namespace LocalJSX {
    interface StencilPlayground {
        /**
          * @default `import { Component, h } from '@stencil/core';  @Component({ tag: 'my-component' }) export class MyComponent {   render() {     return <div>Hello from Stencil!</div>;   } } `
         */
        "code"?: string;
    }
    interface StencilPlaygroundEditor {
        "onValueChange"?: (event: StencilPlaygroundEditorCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface StencilPlaygroundPreview {
        /**
          * @default null
         */
        "compiledCode"?: string | null;
        /**
          * @default null
         */
        "componentTag"?: string | null;
        "onPreviewResult"?: (event: StencilPlaygroundPreviewCustomEvent<PreviewResult>) => void;
    }

    interface StencilPlaygroundAttributes {
        "code": string;
    }
    interface StencilPlaygroundEditorAttributes {
        "value": string;
    }
    interface StencilPlaygroundPreviewAttributes {
        "compiledCode": string | null;
        "componentTag": string | null;
    }

    interface IntrinsicElements {
        "stencil-playground": Omit<StencilPlayground, keyof StencilPlaygroundAttributes> & { [K in keyof StencilPlayground & keyof StencilPlaygroundAttributes]?: StencilPlayground[K] } & { [K in keyof StencilPlayground & keyof StencilPlaygroundAttributes as `attr:${K}`]?: StencilPlaygroundAttributes[K] } & { [K in keyof StencilPlayground & keyof StencilPlaygroundAttributes as `prop:${K}`]?: StencilPlayground[K] };
        "stencil-playground-editor": Omit<StencilPlaygroundEditor, keyof StencilPlaygroundEditorAttributes> & { [K in keyof StencilPlaygroundEditor & keyof StencilPlaygroundEditorAttributes]?: StencilPlaygroundEditor[K] } & { [K in keyof StencilPlaygroundEditor & keyof StencilPlaygroundEditorAttributes as `attr:${K}`]?: StencilPlaygroundEditorAttributes[K] } & { [K in keyof StencilPlaygroundEditor & keyof StencilPlaygroundEditorAttributes as `prop:${K}`]?: StencilPlaygroundEditor[K] };
        "stencil-playground-preview": Omit<StencilPlaygroundPreview, keyof StencilPlaygroundPreviewAttributes> & { [K in keyof StencilPlaygroundPreview & keyof StencilPlaygroundPreviewAttributes]?: StencilPlaygroundPreview[K] } & { [K in keyof StencilPlaygroundPreview & keyof StencilPlaygroundPreviewAttributes as `attr:${K}`]?: StencilPlaygroundPreviewAttributes[K] } & { [K in keyof StencilPlaygroundPreview & keyof StencilPlaygroundPreviewAttributes as `prop:${K}`]?: StencilPlaygroundPreview[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-playground": LocalJSX.IntrinsicElements["stencil-playground"] & JSXBase.HTMLAttributes<HTMLStencilPlaygroundElement>;
            "stencil-playground-editor": LocalJSX.IntrinsicElements["stencil-playground-editor"] & JSXBase.HTMLAttributes<HTMLStencilPlaygroundEditorElement>;
            "stencil-playground-preview": LocalJSX.IntrinsicElements["stencil-playground-preview"] & JSXBase.HTMLAttributes<HTMLStencilPlaygroundPreviewElement>;
        }
    }
}
