export type { StyleExtension } from './types.js';
export { getComponentBoilerplate, toPascalCase } from './generate/component.js';
export { getStyleBoilerplate } from './generate/style.js';
export { getTemplatePath, PROJECT_TEMPLATES } from './project/paths.js';
export type { ProjectTemplateId } from './project/paths.js';
export { generateStencilConfig, generatePackageJsonFields } from './project/config.js';
export type { ConfigSelections, OutputKey, DocKey, PackageJsonFields } from './project/config.js';
export { generateIndexHtml } from './project/index-html.js';
export type { IndexHtmlSelections } from './project/index-html.js';
export { getUsageExampleBoilerplate, getPreviewHtmlBoilerplate } from './generate/preview.js';
