/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
export namespace Components {
    interface HelloWorldLight {
    }
    interface HelloWorldShadow {
        /**
          * @default 'World'
         */
        "name": string;
    }
}
declare global {
    interface HTMLHelloWorldLightElement extends Components.HelloWorldLight, HTMLStencilElement {
    }
    var HTMLHelloWorldLightElement: {
        prototype: HTMLHelloWorldLightElement;
        new (): HTMLHelloWorldLightElement;
    };
    interface HTMLHelloWorldShadowElement extends Components.HelloWorldShadow, HTMLStencilElement {
    }
    var HTMLHelloWorldShadowElement: {
        prototype: HTMLHelloWorldShadowElement;
        new (): HTMLHelloWorldShadowElement;
    };
    interface HTMLElementTagNameMap {
        "hello-world-light": HTMLHelloWorldLightElement;
        "hello-world-shadow": HTMLHelloWorldShadowElement;
    }
}
declare namespace LocalJSX {
    interface HelloWorldLight {
    }
    interface HelloWorldShadow {
        /**
          * @default 'World'
         */
        "name"?: string;
    }

    interface HelloWorldShadowAttributes {
        "name": string;
    }

    interface IntrinsicElements {
        "hello-world-light": HelloWorldLight;
        "hello-world-shadow": Omit<HelloWorldShadow, keyof HelloWorldShadowAttributes> & { [K in keyof HelloWorldShadow & keyof HelloWorldShadowAttributes]?: HelloWorldShadow[K] } & { [K in keyof HelloWorldShadow & keyof HelloWorldShadowAttributes as `attr:${K}`]?: HelloWorldShadowAttributes[K] } & { [K in keyof HelloWorldShadow & keyof HelloWorldShadowAttributes as `prop:${K}`]?: HelloWorldShadow[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hello-world-light": LocalJSX.IntrinsicElements["hello-world-light"] & JSXBase.HTMLAttributes<HTMLHelloWorldLightElement>;
            "hello-world-shadow": LocalJSX.IntrinsicElements["hello-world-shadow"] & JSXBase.HTMLAttributes<HTMLHelloWorldShadowElement>;
        }
    }
}
