packages:
  - 'packages/*'
  - 'test/**/*'

catalog:
  vitest: ^4.1.1
  '@vitest/browser': ^4.0.18
  '@vitest/browser-playwright': ^4.0.18
  '@playwright/test': ^1.52.0
  '@stencil/vitest': '^1.9.2'
  "vitest-environment-stencil": "^1.9.2"
  '@stencil/playwright': '1.2.3-next.11'
  playwright: ^1.52.0
  tsdown: '^0.21.0'
  typescript: '~5.9.3'