packages:
  - 'packages/*'
  - 'test/**/*'

catalog:
  vitest: ^4.1.1
  '@vitest/browser': ^4.1.1
  '@vitest/browser-playwright': ^4.1.1
  '@playwright/test': ^1.52.0
  '@stencil/vitest': '^1.11.6'
  'vitest-environment-stencil': '^1.11.6'
  '@stencil/playwright': '~0.3.1'
  playwright: ^1.58.0
  tsdown: '^0.21.7'
  typescript: '~6.0.2'
