const noColor = !process.stdout.isTTY || 'NO_COLOR' in process.env;

const RESET = noColor ? '' : '\x1b[0m';
const BG = noColor ? '' : '\x1b[38;2;60;44;255m'; // #3c2cff

const RAW = `\
              .............              
           ...................          
        .........................        
     ..............................     
    .................................    
   ..............████████████.........   
  .............████████████............  
 ............████████████............... 
...........***************...............
.........████████████████████████████....
.......████████████████████████████......
.....████████████████████████████........
...████████████████████████████..........
...............**************............
 ..............████████████.............
 ............████████████.............. 
  .........████████████...............  
    .................................   
     ..............................     
       ..........................       
         ......................         
            ................`;

function colorize(raw: string): string {
  if (noColor) return raw;

  let out = '';
  let style = '';

  for (const ch of raw) {
    const next = '.*'.includes(ch) ? BG : '';
    if (next !== style) {
      if (style) out += RESET;
      if (next) out += next;
      style = next;
    }
    out += ch;
  }

  return style ? out + RESET : out;
}

export const SPLASH = colorize(RAW);

export function printSplash(): void {
  if (!process.stdout.isTTY) return;
  process.stdout.write('\n' + SPLASH + '\n\n');
}
