import pkg from '../../package.json' with { type: 'json' };

const CLI_VERSION: string = pkg.version;

const isTTY = process.stdout.isTTY;
const noColor = !isTTY || 'NO_COLOR' in process.env;

const RESET = noColor ? '' : '\x1b[0m';
const BOLD = noColor ? '' : '\x1b[1m';
const DIM = noColor ? '' : '\x1b[2m';
const BLUE = noColor ? '' : '\x1b[38;2;60;44;255m';

const RAW = `\
              .............
           ...................
        .........................
     ..............................
    .................................
   ..............████████████.........
  .............████████████............
 ............████████████...............
...........*************.................
.........████████████████████████████....
.......████████████████████████████......
.....████████████████████████████........
...████████████████████████████..........
................*************............
 ..............████████████.............
 ............████████████..............
  .........████████████...............
    .................................
     ..............................
       ..........................
         ......................
            ................`;

function colorize(raw: string) {
  if (noColor) return raw;

  let out = '';
  let style = '';

  for (const ch of raw) {
    const next = '.*'.includes(ch) ? BLUE : '';
    if (next !== style) {
      if (style) out += RESET;
      if (next) out += next;
      style = next;
    }
    out += ch;
  }

  return style ? out + RESET : out;
}

const SPLASH = colorize(RAW);

export function printSplash() {
  if (!isTTY) return;
  const header = `  ${BOLD}Stencil${RESET}  ${BLUE}v${CLI_VERSION}${RESET}`;
  const tagline = `  ${DIM}The Custom Element Compiler${RESET}`;
  process.stdout.write(`\n${SPLASH}\n\n${header}\n${tagline}\n\n`);
}
