/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SiblingExtended {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface SiblingExtendedBase {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface SiblingRoot {
    }
}
declare global {
    interface HTMLSiblingExtendedElement extends Components.SiblingExtended, HTMLStencilElement {
    }
    var HTMLSiblingExtendedElement: {
        prototype: HTMLSiblingExtendedElement;
        new (): HTMLSiblingExtendedElement;
    };
    interface HTMLSiblingExtendedBaseElement extends Components.SiblingExtendedBase, HTMLStencilElement {
    }
    var HTMLSiblingExtendedBaseElement: {
        prototype: HTMLSiblingExtendedBaseElement;
        new (): HTMLSiblingExtendedBaseElement;
    };
    interface HTMLSiblingRootElement extends Components.SiblingRoot, HTMLStencilElement {
    }
    var HTMLSiblingRootElement: {
        prototype: HTMLSiblingRootElement;
        new (): HTMLSiblingRootElement;
    };
    interface HTMLElementTagNameMap {
        "sibling-extended": HTMLSiblingExtendedElement;
        "sibling-extended-base": HTMLSiblingExtendedBaseElement;
        "sibling-root": HTMLSiblingRootElement;
    }
}
declare namespace LocalJSX {
    interface SiblingExtended {
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface SiblingExtendedBase {
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface SiblingRoot {
    }
    interface IntrinsicElements {
        "sibling-extended": SiblingExtended;
        "sibling-extended-base": SiblingExtendedBase;
        "sibling-root": SiblingRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sibling-extended": LocalJSX.SiblingExtended & JSXBase.HTMLAttributes<HTMLSiblingExtendedElement>;
            "sibling-extended-base": LocalJSX.SiblingExtendedBase & JSXBase.HTMLAttributes<HTMLSiblingExtendedBaseElement>;
            "sibling-root": LocalJSX.SiblingRoot & JSXBase.HTMLAttributes<HTMLSiblingRootElement>;
        }
    }
}
