/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
export namespace Components {
    interface LitContextConsumer {
    }
    interface LitContextProvider {
    }
}
declare global {
    interface HTMLLitContextConsumerElement extends Components.LitContextConsumer, HTMLStencilElement {
    }
    var HTMLLitContextConsumerElement: {
        prototype: HTMLLitContextConsumerElement;
        new (): HTMLLitContextConsumerElement;
    };
    interface HTMLLitContextProviderElement extends Components.LitContextProvider, HTMLStencilElement {
    }
    var HTMLLitContextProviderElement: {
        prototype: HTMLLitContextProviderElement;
        new (): HTMLLitContextProviderElement;
    };
    interface HTMLElementTagNameMap {
        "lit-context-consumer": HTMLLitContextConsumerElement;
        "lit-context-provider": HTMLLitContextProviderElement;
    }
}
declare namespace LocalJSX {
    interface LitContextConsumer {
    }
    interface LitContextProvider {
    }
    interface IntrinsicElements {
        "lit-context-consumer": LitContextConsumer;
        "lit-context-provider": LitContextProvider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lit-context-consumer": LocalJSX.IntrinsicElements["lit-context-consumer"] & JSXBase.HTMLAttributes<HTMLLitContextConsumerElement>;
            "lit-context-provider": LocalJSX.IntrinsicElements["lit-context-provider"] & JSXBase.HTMLAttributes<HTMLLitContextProviderElement>;
        }
    }
}
