/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
export namespace Components {
    interface MyApp {
        /**
          * @default 0
         */
        "offset": number;
    }
    interface MyItem {
        /**
          * @default 0
         */
        "index": number;
    }
    interface MyList {
        /**
          * @default 0
         */
        "offset": number;
    }
}
declare global {
    interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {
    }
    var HTMLMyAppElement: {
        prototype: HTMLMyAppElement;
        new (): HTMLMyAppElement;
    };
    interface HTMLMyItemElement extends Components.MyItem, HTMLStencilElement {
    }
    var HTMLMyItemElement: {
        prototype: HTMLMyItemElement;
        new (): HTMLMyItemElement;
    };
    interface HTMLMyListElement extends Components.MyList, HTMLStencilElement {
    }
    var HTMLMyListElement: {
        prototype: HTMLMyListElement;
        new (): HTMLMyListElement;
    };
    interface HTMLElementTagNameMap {
        "my-app": HTMLMyAppElement;
        "my-item": HTMLMyItemElement;
        "my-list": HTMLMyListElement;
    }
}
declare namespace LocalJSX {
    interface MyApp {
        /**
          * @default 0
         */
        "offset"?: number;
    }
    interface MyItem {
        /**
          * @default 0
         */
        "index"?: number;
    }
    interface MyList {
        /**
          * @default 0
         */
        "offset"?: number;
    }

    interface MyAppAttributes {
        "offset": number;
    }
    interface MyItemAttributes {
        "index": number;
    }
    interface MyListAttributes {
        "offset": number;
    }

    interface IntrinsicElements {
        "my-app": Omit<MyApp, keyof MyAppAttributes> & { [K in keyof MyApp & keyof MyAppAttributes]?: MyApp[K] } & { [K in keyof MyApp & keyof MyAppAttributes as `attr:${K}`]?: MyAppAttributes[K] } & { [K in keyof MyApp & keyof MyAppAttributes as `prop:${K}`]?: MyApp[K] };
        "my-item": Omit<MyItem, keyof MyItemAttributes> & { [K in keyof MyItem & keyof MyItemAttributes]?: MyItem[K] } & { [K in keyof MyItem & keyof MyItemAttributes as `attr:${K}`]?: MyItemAttributes[K] } & { [K in keyof MyItem & keyof MyItemAttributes as `prop:${K}`]?: MyItem[K] };
        "my-list": Omit<MyList, keyof MyListAttributes> & { [K in keyof MyList & keyof MyListAttributes]?: MyList[K] } & { [K in keyof MyList & keyof MyListAttributes as `attr:${K}`]?: MyListAttributes[K] } & { [K in keyof MyList & keyof MyListAttributes as `prop:${K}`]?: MyList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-app": LocalJSX.IntrinsicElements["my-app"] & JSXBase.HTMLAttributes<HTMLMyAppElement>;
            "my-item": LocalJSX.IntrinsicElements["my-item"] & JSXBase.HTMLAttributes<HTMLMyItemElement>;
            "my-list": LocalJSX.IntrinsicElements["my-list"] & JSXBase.HTMLAttributes<HTMLMyListElement>;
        }
    }
}
