export {
  // Decorator stubs (compile-time metadata, no-op at runtime)
  AttachInternals,
  AttrDeserialize,
  Component,
  Element,
  Event,
  Listen,
  Method,
  Prop,
  PropSerialize,
  resolveVar,
  State,
  Watch,
  // Runtime exports
  Build,
  Fragment,
  forceUpdate,
  getAssetPath,
  getElement,
  getShadowRoot,
  getMode,
  getRenderingRef,
  h,
  Host,
  injectSideEffectStyle,
  Mixin,
  readTask,
  ReactiveControllerHost,
  registerSideEffectStyleTarget,
  render,
  setAssetPath,
  setErrorHandler,
  setMode,
  setPlatformHelpers,
  setTagTransformer,
  transformTag,
  unregisterSideEffectStyleTarget,
  writeTask,
} from './client/index.js';
