/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
export namespace Components {
    /**
     * `componentWillLoad` awaits a Promise that never settles, to test how `renderToString()`
     * behaves under the `ssr-wasm` target when a component's hydration never settles on its own -
     * see ssr-wasm.e2e.ts.
     */
    interface HangsForeverCmp {
    }
    interface MyGreeting {
        /**
          * @default 'World'
         */
        "name": string;
    }
}
declare global {
    /**
     * `componentWillLoad` awaits a Promise that never settles, to test how `renderToString()`
     * behaves under the `ssr-wasm` target when a component's hydration never settles on its own -
     * see ssr-wasm.e2e.ts.
     */
    interface HTMLHangsForeverCmpElement extends Components.HangsForeverCmp, HTMLStencilElement {
    }
    var HTMLHangsForeverCmpElement: {
        prototype: HTMLHangsForeverCmpElement;
        new (): HTMLHangsForeverCmpElement;
    };
    interface HTMLMyGreetingElement extends Components.MyGreeting, HTMLStencilElement {
    }
    var HTMLMyGreetingElement: {
        prototype: HTMLMyGreetingElement;
        new (): HTMLMyGreetingElement;
    };
    interface HTMLElementTagNameMap {
        "hangs-forever-cmp": HTMLHangsForeverCmpElement;
        "my-greeting": HTMLMyGreetingElement;
    }
}
declare namespace LocalJSX {
    /**
     * `componentWillLoad` awaits a Promise that never settles, to test how `renderToString()`
     * behaves under the `ssr-wasm` target when a component's hydration never settles on its own -
     * see ssr-wasm.e2e.ts.
     */
    interface HangsForeverCmp {
    }
    interface MyGreeting {
        /**
          * @default 'World'
         */
        "name"?: string;
    }

    interface MyGreetingAttributes {
        "name": string;
    }

    interface IntrinsicElements {
        "hangs-forever-cmp": HangsForeverCmp;
        "my-greeting": Omit<MyGreeting, keyof MyGreetingAttributes> & { [K in keyof MyGreeting & keyof MyGreetingAttributes]?: MyGreeting[K] } & { [K in keyof MyGreeting & keyof MyGreetingAttributes as `attr:${K}`]?: MyGreetingAttributes[K] } & { [K in keyof MyGreeting & keyof MyGreetingAttributes as `prop:${K}`]?: MyGreeting[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * `componentWillLoad` awaits a Promise that never settles, to test how `renderToString()`
             * behaves under the `ssr-wasm` target when a component's hydration never settles on its own -
             * see ssr-wasm.e2e.ts.
             */
            "hangs-forever-cmp": LocalJSX.IntrinsicElements["hangs-forever-cmp"] & JSXBase.HTMLAttributes<HTMLHangsForeverCmpElement>;
            "my-greeting": LocalJSX.IntrinsicElements["my-greeting"] & JSXBase.HTMLAttributes<HTMLMyGreetingElement>;
        }
    }
}
