/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
export namespace Components {
    interface MyGreeting {
        /**
          * @default 'World'
         */
        "name": string;
    }
}
declare global {
    interface HTMLMyGreetingElement extends Components.MyGreeting, HTMLStencilElement {
    }
    var HTMLMyGreetingElement: {
        prototype: HTMLMyGreetingElement;
        new (): HTMLMyGreetingElement;
    };
    interface HTMLElementTagNameMap {
        "my-greeting": HTMLMyGreetingElement;
    }
}
declare namespace LocalJSX {
    interface MyGreeting {
        /**
          * @default 'World'
         */
        "name"?: string;
    }

    interface MyGreetingAttributes {
        "name": string;
    }

    interface IntrinsicElements {
        "my-greeting": Omit<MyGreeting, keyof MyGreetingAttributes> & { [K in keyof MyGreeting & keyof MyGreetingAttributes]?: MyGreeting[K] } & { [K in keyof MyGreeting & keyof MyGreetingAttributes as `attr:${K}`]?: MyGreetingAttributes[K] } & { [K in keyof MyGreeting & keyof MyGreetingAttributes as `prop:${K}`]?: MyGreeting[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-greeting": LocalJSX.IntrinsicElements["my-greeting"] & JSXBase.HTMLAttributes<HTMLMyGreetingElement>;
        }
    }
}
