/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
import { CarData } from "./__fixtures__/car-data";
import { CarData as CarData1 } from "./car-list/car-data";
export { CarData } from "./__fixtures__/car-data";
export { CarData as CarData1 } from "./car-list/car-data";
export namespace Components {
    interface AnotherCarDetail {
        "car": CarData;
    }
    /**
     * Component that helps display a list of cars
     */
    interface AnotherCarList {
        "cars": CarData[];
        "selected": CarData;
    }
    interface CarDetail {
        "car": CarData1;
    }
    /**
     * Component that helps display a list of cars
     */
    interface CarList {
        "cars": CarData1[];
        "selected": CarData1;
    }
    interface CmpDsd {
        /**
          * @default 0
         */
        "initialCounter": number;
    }
    interface CmpDsdFocus {
    }
    interface CmpServerVsClient {
    }
    interface CmpWithSlot {
    }
    interface ComplexProperties {
        /**
          * map objects
         */
        "baz": Map<string, { qux: symbol }>;
        /**
          * basic object
         */
        "foo": { bar: string; loo: number[]; qux: { quux: symbol } };
        /**
          * infinity
         */
        "grault": typeof Infinity;
        /**
          * basic array
         */
        "kidsNames": any;
        /**
          * set objects
         */
        "quux": Set<string>;
        /**
          * null
         */
        "waldo": null;
    }
    interface DsdListenCmp {
    }
    interface HydratedSiblingAccessors {
    }
    interface MyCmp {
        /**
          * bar prop
          * @returns bar
          * @readonly 
          * @default 'bar'
         */
        "barProp": string;
        /**
          * foo prop
         */
        "fooProp": string;
        /**
          * Mode
         */
        "mode"?: any;
    }
    interface MyJsxCmp {
        /**
          * bar prop
          * @returns bar
          * @readonly 
          * @default 'bar'
         */
        "barProp": string;
        /**
          * foo prop
         */
        "fooProp": string;
        /**
          * Mode
         */
        "mode"?: any;
    }
    interface NestedCmpChild {
    }
    interface NestedCmpParent {
    }
    interface NestedScopeCmp {
    }
    interface NonShadowChild {
    }
    interface NonShadowForwardedSlot {
    }
    interface NonShadowMultiSlots {
    }
    interface NonShadowWrapper {
    }
    interface PartSsrShadowCmp {
        "selected": boolean;
    }
    interface PartWrapSsrShadowCmp {
        "selected": boolean;
    }
    interface PrerenderCmp {
    }
    interface PropCmp {
        /**
          * @default 'life preservers'
         */
        "clothes": string;
        "first": string;
        /**
          * @readonly
         */
        "fullName": string;
        "lastName": string;
        /**
          * Mode
         */
        "mode"?: any;
    }
    interface RuntimeDecorators {
        /**
          * @default 'basicProp'
         */
        "basicProp": string;
        "decoratedGetterSetterProp": number;
        /**
          * @default -10
         */
        "decoratedProp": number;
    }
    interface ScopedCarDetail {
        "car": CarData;
    }
    /**
     * Component that helps display a list of cars
     */
    interface ScopedCarList {
        "cars": CarData[];
        "selected": CarData;
    }
    interface ScopedSsrChildCmp {
    }
    interface ScopedSsrParentCmp {
    }
    interface SerializeDeserializer {
        "array": string[];
        "getArray": () => Promise<any>;
        "getGetSet": () => Promise<any[]>;
        "getSet": { [key: string]: string; };
        "reset": () => Promise<void>;
    }
    interface ShadowChild {
    }
    interface ShadowSsrChildCmp {
    }
    interface ShadowSsrParentCmp {
    }
    interface ShadowWrapper {
    }
    interface SlowSsrProp {
        /**
          * @default []
         */
        "anArray": any[];
    }
    interface SsrOrderCmp {
    }
    interface SsrOrderWrapCmp {
    }
    interface SsrShadowCmp {
        "selected": boolean;
    }
    interface WrapSsrShadowCmp {
        "selected": boolean;
    }
}
export interface AnotherCarListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAnotherCarListElement;
}
export interface CarListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCarListElement;
}
export interface ScopedCarListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScopedCarListElement;
}
declare global {
    interface HTMLAnotherCarDetailElement extends Components.AnotherCarDetail, HTMLStencilElement {
    }
    var HTMLAnotherCarDetailElement: {
        prototype: HTMLAnotherCarDetailElement;
        new (): HTMLAnotherCarDetailElement;
    };
    interface HTMLAnotherCarListElementEventMap {
        "carSelected": CarData;
    }
    /**
     * Component that helps display a list of cars
     */
    interface HTMLAnotherCarListElement extends Components.AnotherCarList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAnotherCarListElementEventMap>(type: K, listener: (this: HTMLAnotherCarListElement, ev: AnotherCarListCustomEvent<HTMLAnotherCarListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAnotherCarListElementEventMap>(type: K, listener: (this: HTMLAnotherCarListElement, ev: AnotherCarListCustomEvent<HTMLAnotherCarListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAnotherCarListElement: {
        prototype: HTMLAnotherCarListElement;
        new (): HTMLAnotherCarListElement;
    };
    interface HTMLCarDetailElement extends Components.CarDetail, HTMLStencilElement {
    }
    var HTMLCarDetailElement: {
        prototype: HTMLCarDetailElement;
        new (): HTMLCarDetailElement;
    };
    interface HTMLCarListElementEventMap {
        "carSelected": CarData1;
    }
    /**
     * Component that helps display a list of cars
     */
    interface HTMLCarListElement extends Components.CarList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCarListElementEventMap>(type: K, listener: (this: HTMLCarListElement, ev: CarListCustomEvent<HTMLCarListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCarListElementEventMap>(type: K, listener: (this: HTMLCarListElement, ev: CarListCustomEvent<HTMLCarListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCarListElement: {
        prototype: HTMLCarListElement;
        new (): HTMLCarListElement;
    };
    interface HTMLCmpDsdElement extends Components.CmpDsd, HTMLStencilElement {
    }
    var HTMLCmpDsdElement: {
        prototype: HTMLCmpDsdElement;
        new (): HTMLCmpDsdElement;
    };
    interface HTMLCmpDsdFocusElement extends Components.CmpDsdFocus, HTMLStencilElement {
    }
    var HTMLCmpDsdFocusElement: {
        prototype: HTMLCmpDsdFocusElement;
        new (): HTMLCmpDsdFocusElement;
    };
    interface HTMLCmpServerVsClientElement extends Components.CmpServerVsClient, HTMLStencilElement {
    }
    var HTMLCmpServerVsClientElement: {
        prototype: HTMLCmpServerVsClientElement;
        new (): HTMLCmpServerVsClientElement;
    };
    interface HTMLCmpWithSlotElement extends Components.CmpWithSlot, HTMLStencilElement {
    }
    var HTMLCmpWithSlotElement: {
        prototype: HTMLCmpWithSlotElement;
        new (): HTMLCmpWithSlotElement;
    };
    interface HTMLComplexPropertiesElement extends Components.ComplexProperties, HTMLStencilElement {
    }
    var HTMLComplexPropertiesElement: {
        prototype: HTMLComplexPropertiesElement;
        new (): HTMLComplexPropertiesElement;
    };
    interface HTMLDsdListenCmpElement extends Components.DsdListenCmp, HTMLStencilElement {
    }
    var HTMLDsdListenCmpElement: {
        prototype: HTMLDsdListenCmpElement;
        new (): HTMLDsdListenCmpElement;
    };
    interface HTMLHydratedSiblingAccessorsElement extends Components.HydratedSiblingAccessors, HTMLStencilElement {
    }
    var HTMLHydratedSiblingAccessorsElement: {
        prototype: HTMLHydratedSiblingAccessorsElement;
        new (): HTMLHydratedSiblingAccessorsElement;
    };
    interface HTMLMyCmpElement extends Components.MyCmp, HTMLStencilElement {
    }
    var HTMLMyCmpElement: {
        prototype: HTMLMyCmpElement;
        new (): HTMLMyCmpElement;
    };
    interface HTMLMyJsxCmpElement extends Components.MyJsxCmp, HTMLStencilElement {
    }
    var HTMLMyJsxCmpElement: {
        prototype: HTMLMyJsxCmpElement;
        new (): HTMLMyJsxCmpElement;
    };
    interface HTMLNestedCmpChildElement extends Components.NestedCmpChild, HTMLStencilElement {
    }
    var HTMLNestedCmpChildElement: {
        prototype: HTMLNestedCmpChildElement;
        new (): HTMLNestedCmpChildElement;
    };
    interface HTMLNestedCmpParentElement extends Components.NestedCmpParent, HTMLStencilElement {
    }
    var HTMLNestedCmpParentElement: {
        prototype: HTMLNestedCmpParentElement;
        new (): HTMLNestedCmpParentElement;
    };
    interface HTMLNestedScopeCmpElement extends Components.NestedScopeCmp, HTMLStencilElement {
    }
    var HTMLNestedScopeCmpElement: {
        prototype: HTMLNestedScopeCmpElement;
        new (): HTMLNestedScopeCmpElement;
    };
    interface HTMLNonShadowChildElement extends Components.NonShadowChild, HTMLStencilElement {
    }
    var HTMLNonShadowChildElement: {
        prototype: HTMLNonShadowChildElement;
        new (): HTMLNonShadowChildElement;
    };
    interface HTMLNonShadowForwardedSlotElement extends Components.NonShadowForwardedSlot, HTMLStencilElement {
    }
    var HTMLNonShadowForwardedSlotElement: {
        prototype: HTMLNonShadowForwardedSlotElement;
        new (): HTMLNonShadowForwardedSlotElement;
    };
    interface HTMLNonShadowMultiSlotsElement extends Components.NonShadowMultiSlots, HTMLStencilElement {
    }
    var HTMLNonShadowMultiSlotsElement: {
        prototype: HTMLNonShadowMultiSlotsElement;
        new (): HTMLNonShadowMultiSlotsElement;
    };
    interface HTMLNonShadowWrapperElement extends Components.NonShadowWrapper, HTMLStencilElement {
    }
    var HTMLNonShadowWrapperElement: {
        prototype: HTMLNonShadowWrapperElement;
        new (): HTMLNonShadowWrapperElement;
    };
    interface HTMLPartSsrShadowCmpElement extends Components.PartSsrShadowCmp, HTMLStencilElement {
    }
    var HTMLPartSsrShadowCmpElement: {
        prototype: HTMLPartSsrShadowCmpElement;
        new (): HTMLPartSsrShadowCmpElement;
    };
    interface HTMLPartWrapSsrShadowCmpElement extends Components.PartWrapSsrShadowCmp, HTMLStencilElement {
    }
    var HTMLPartWrapSsrShadowCmpElement: {
        prototype: HTMLPartWrapSsrShadowCmpElement;
        new (): HTMLPartWrapSsrShadowCmpElement;
    };
    interface HTMLPrerenderCmpElement extends Components.PrerenderCmp, HTMLStencilElement {
    }
    var HTMLPrerenderCmpElement: {
        prototype: HTMLPrerenderCmpElement;
        new (): HTMLPrerenderCmpElement;
    };
    interface HTMLPropCmpElement extends Components.PropCmp, HTMLStencilElement {
    }
    var HTMLPropCmpElement: {
        prototype: HTMLPropCmpElement;
        new (): HTMLPropCmpElement;
    };
    interface HTMLRuntimeDecoratorsElement extends Components.RuntimeDecorators, HTMLStencilElement {
    }
    var HTMLRuntimeDecoratorsElement: {
        prototype: HTMLRuntimeDecoratorsElement;
        new (): HTMLRuntimeDecoratorsElement;
    };
    interface HTMLScopedCarDetailElement extends Components.ScopedCarDetail, HTMLStencilElement {
    }
    var HTMLScopedCarDetailElement: {
        prototype: HTMLScopedCarDetailElement;
        new (): HTMLScopedCarDetailElement;
    };
    interface HTMLScopedCarListElementEventMap {
        "carSelected": CarData;
    }
    /**
     * Component that helps display a list of cars
     */
    interface HTMLScopedCarListElement extends Components.ScopedCarList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScopedCarListElementEventMap>(type: K, listener: (this: HTMLScopedCarListElement, ev: ScopedCarListCustomEvent<HTMLScopedCarListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScopedCarListElementEventMap>(type: K, listener: (this: HTMLScopedCarListElement, ev: ScopedCarListCustomEvent<HTMLScopedCarListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScopedCarListElement: {
        prototype: HTMLScopedCarListElement;
        new (): HTMLScopedCarListElement;
    };
    interface HTMLScopedSsrChildCmpElement extends Components.ScopedSsrChildCmp, HTMLStencilElement {
    }
    var HTMLScopedSsrChildCmpElement: {
        prototype: HTMLScopedSsrChildCmpElement;
        new (): HTMLScopedSsrChildCmpElement;
    };
    interface HTMLScopedSsrParentCmpElement extends Components.ScopedSsrParentCmp, HTMLStencilElement {
    }
    var HTMLScopedSsrParentCmpElement: {
        prototype: HTMLScopedSsrParentCmpElement;
        new (): HTMLScopedSsrParentCmpElement;
    };
    interface HTMLSerializeDeserializerElement extends Components.SerializeDeserializer, HTMLStencilElement {
    }
    var HTMLSerializeDeserializerElement: {
        prototype: HTMLSerializeDeserializerElement;
        new (): HTMLSerializeDeserializerElement;
    };
    interface HTMLShadowChildElement extends Components.ShadowChild, HTMLStencilElement {
    }
    var HTMLShadowChildElement: {
        prototype: HTMLShadowChildElement;
        new (): HTMLShadowChildElement;
    };
    interface HTMLShadowSsrChildCmpElement extends Components.ShadowSsrChildCmp, HTMLStencilElement {
    }
    var HTMLShadowSsrChildCmpElement: {
        prototype: HTMLShadowSsrChildCmpElement;
        new (): HTMLShadowSsrChildCmpElement;
    };
    interface HTMLShadowSsrParentCmpElement extends Components.ShadowSsrParentCmp, HTMLStencilElement {
    }
    var HTMLShadowSsrParentCmpElement: {
        prototype: HTMLShadowSsrParentCmpElement;
        new (): HTMLShadowSsrParentCmpElement;
    };
    interface HTMLShadowWrapperElement extends Components.ShadowWrapper, HTMLStencilElement {
    }
    var HTMLShadowWrapperElement: {
        prototype: HTMLShadowWrapperElement;
        new (): HTMLShadowWrapperElement;
    };
    interface HTMLSlowSsrPropElement extends Components.SlowSsrProp, HTMLStencilElement {
    }
    var HTMLSlowSsrPropElement: {
        prototype: HTMLSlowSsrPropElement;
        new (): HTMLSlowSsrPropElement;
    };
    interface HTMLSsrOrderCmpElement extends Components.SsrOrderCmp, HTMLStencilElement {
    }
    var HTMLSsrOrderCmpElement: {
        prototype: HTMLSsrOrderCmpElement;
        new (): HTMLSsrOrderCmpElement;
    };
    interface HTMLSsrOrderWrapCmpElement extends Components.SsrOrderWrapCmp, HTMLStencilElement {
    }
    var HTMLSsrOrderWrapCmpElement: {
        prototype: HTMLSsrOrderWrapCmpElement;
        new (): HTMLSsrOrderWrapCmpElement;
    };
    interface HTMLSsrShadowCmpElement extends Components.SsrShadowCmp, HTMLStencilElement {
    }
    var HTMLSsrShadowCmpElement: {
        prototype: HTMLSsrShadowCmpElement;
        new (): HTMLSsrShadowCmpElement;
    };
    interface HTMLWrapSsrShadowCmpElement extends Components.WrapSsrShadowCmp, HTMLStencilElement {
    }
    var HTMLWrapSsrShadowCmpElement: {
        prototype: HTMLWrapSsrShadowCmpElement;
        new (): HTMLWrapSsrShadowCmpElement;
    };
    interface HTMLElementTagNameMap {
        "another-car-detail": HTMLAnotherCarDetailElement;
        "another-car-list": HTMLAnotherCarListElement;
        "car-detail": HTMLCarDetailElement;
        "car-list": HTMLCarListElement;
        "cmp-dsd": HTMLCmpDsdElement;
        "cmp-dsd-focus": HTMLCmpDsdFocusElement;
        "cmp-server-vs-client": HTMLCmpServerVsClientElement;
        "cmp-with-slot": HTMLCmpWithSlotElement;
        "complex-properties": HTMLComplexPropertiesElement;
        "dsd-listen-cmp": HTMLDsdListenCmpElement;
        "hydrated-sibling-accessors": HTMLHydratedSiblingAccessorsElement;
        "my-cmp": HTMLMyCmpElement;
        "my-jsx-cmp": HTMLMyJsxCmpElement;
        "nested-cmp-child": HTMLNestedCmpChildElement;
        "nested-cmp-parent": HTMLNestedCmpParentElement;
        "nested-scope-cmp": HTMLNestedScopeCmpElement;
        "non-shadow-child": HTMLNonShadowChildElement;
        "non-shadow-forwarded-slot": HTMLNonShadowForwardedSlotElement;
        "non-shadow-multi-slots": HTMLNonShadowMultiSlotsElement;
        "non-shadow-wrapper": HTMLNonShadowWrapperElement;
        "part-ssr-shadow-cmp": HTMLPartSsrShadowCmpElement;
        "part-wrap-ssr-shadow-cmp": HTMLPartWrapSsrShadowCmpElement;
        "prerender-cmp": HTMLPrerenderCmpElement;
        "prop-cmp": HTMLPropCmpElement;
        "runtime-decorators": HTMLRuntimeDecoratorsElement;
        "scoped-car-detail": HTMLScopedCarDetailElement;
        "scoped-car-list": HTMLScopedCarListElement;
        "scoped-ssr-child-cmp": HTMLScopedSsrChildCmpElement;
        "scoped-ssr-parent-cmp": HTMLScopedSsrParentCmpElement;
        "serialize-deserializer": HTMLSerializeDeserializerElement;
        "shadow-child": HTMLShadowChildElement;
        "shadow-ssr-child-cmp": HTMLShadowSsrChildCmpElement;
        "shadow-ssr-parent-cmp": HTMLShadowSsrParentCmpElement;
        "shadow-wrapper": HTMLShadowWrapperElement;
        "slow-ssr-prop": HTMLSlowSsrPropElement;
        "ssr-order-cmp": HTMLSsrOrderCmpElement;
        "ssr-order-wrap-cmp": HTMLSsrOrderWrapCmpElement;
        "ssr-shadow-cmp": HTMLSsrShadowCmpElement;
        "wrap-ssr-shadow-cmp": HTMLWrapSsrShadowCmpElement;
    }
}
declare namespace LocalJSX {
    interface AnotherCarDetail {
        "car"?: CarData;
    }
    /**
     * Component that helps display a list of cars
     */
    interface AnotherCarList {
        "cars"?: CarData[];
        "onCarSelected"?: (event: AnotherCarListCustomEvent<CarData>) => void;
        "selected"?: CarData;
    }
    interface CarDetail {
        "car"?: CarData1;
    }
    /**
     * Component that helps display a list of cars
     */
    interface CarList {
        "cars"?: CarData1[];
        "onCarSelected"?: (event: CarListCustomEvent<CarData1>) => void;
        "selected"?: CarData1;
    }
    interface CmpDsd {
        /**
          * @default 0
         */
        "initialCounter"?: number;
    }
    interface CmpDsdFocus {
    }
    interface CmpServerVsClient {
    }
    interface CmpWithSlot {
    }
    interface ComplexProperties {
        /**
          * map objects
         */
        "baz"?: Map<string, { qux: symbol }>;
        /**
          * basic object
         */
        "foo"?: { bar: string; loo: number[]; qux: { quux: symbol } };
        /**
          * infinity
         */
        "grault"?: typeof Infinity;
        /**
          * basic array
         */
        "kidsNames"?: any;
        /**
          * set objects
         */
        "quux"?: Set<string>;
        /**
          * null
         */
        "waldo"?: null;
    }
    interface DsdListenCmp {
    }
    interface HydratedSiblingAccessors {
    }
    interface MyCmp {
        /**
          * bar prop
          * @returns bar
          * @readonly 
          * @default 'bar'
         */
        "barProp"?: string;
        /**
          * foo prop
         */
        "fooProp"?: string;
        /**
          * Mode
         */
        "mode"?: any;
    }
    interface MyJsxCmp {
        /**
          * bar prop
          * @returns bar
          * @readonly 
          * @default 'bar'
         */
        "barProp"?: string;
        /**
          * foo prop
         */
        "fooProp"?: string;
        /**
          * Mode
         */
        "mode"?: any;
    }
    interface NestedCmpChild {
    }
    interface NestedCmpParent {
    }
    interface NestedScopeCmp {
    }
    interface NonShadowChild {
    }
    interface NonShadowForwardedSlot {
    }
    interface NonShadowMultiSlots {
    }
    interface NonShadowWrapper {
    }
    interface PartSsrShadowCmp {
        "selected"?: boolean;
    }
    interface PartWrapSsrShadowCmp {
        "selected"?: boolean;
    }
    interface PrerenderCmp {
    }
    interface PropCmp {
        /**
          * @default 'life preservers'
         */
        "clothes"?: string;
        "first"?: string;
        /**
          * @readonly
         */
        "fullName"?: string;
        "lastName"?: string;
        /**
          * Mode
         */
        "mode"?: any;
    }
    interface RuntimeDecorators {
        /**
          * @default 'basicProp'
         */
        "basicProp"?: string;
        "decoratedGetterSetterProp"?: number;
        /**
          * @default -10
         */
        "decoratedProp"?: number;
    }
    interface ScopedCarDetail {
        "car"?: CarData;
    }
    /**
     * Component that helps display a list of cars
     */
    interface ScopedCarList {
        "cars"?: CarData[];
        "onCarSelected"?: (event: ScopedCarListCustomEvent<CarData>) => void;
        "selected"?: CarData;
    }
    interface ScopedSsrChildCmp {
    }
    interface ScopedSsrParentCmp {
    }
    interface SerializeDeserializer {
        "array"?: string[];
        "getSet"?: { [key: string]: string; };
    }
    interface ShadowChild {
    }
    interface ShadowSsrChildCmp {
    }
    interface ShadowSsrParentCmp {
    }
    interface ShadowWrapper {
    }
    interface SlowSsrProp {
        /**
          * @default []
         */
        "anArray"?: any[];
    }
    interface SsrOrderCmp {
    }
    interface SsrOrderWrapCmp {
    }
    interface SsrShadowCmp {
        "selected"?: boolean;
    }
    interface WrapSsrShadowCmp {
        "selected"?: boolean;
    }

    interface AnotherCarDetailAttributes {
        "car": string;
    }
    interface AnotherCarListAttributes {
        "cars": string;
    }
    interface CarDetailAttributes {
        "car": string;
    }
    interface CarListAttributes {
        "cars": string;
    }
    interface CmpDsdAttributes {
        "initialCounter": number;
    }
    interface ComplexPropertiesAttributes {
        "grault": typeof Infinity;
        "kidsNames": string;
    }
    interface MyCmpAttributes {
        "fooProp": string;
        "barProp": string;
    }
    interface MyJsxCmpAttributes {
        "fooProp": string;
        "barProp": string;
    }
    interface PartSsrShadowCmpAttributes {
        "selected": boolean;
    }
    interface PartWrapSsrShadowCmpAttributes {
        "selected": boolean;
    }
    interface PropCmpAttributes {
        "first": string;
        "lastName": string;
        "fullName": string;
        "clothes": string;
    }
    interface RuntimeDecoratorsAttributes {
        "basicProp": string;
        "decoratedProp": number;
        "decoratedGetterSetterProp": number;
    }
    interface ScopedCarDetailAttributes {
        "car": string;
    }
    interface ScopedCarListAttributes {
        "cars": string;
    }
    interface SerializeDeserializerAttributes {
        "array": string;
        "getSet": string;
    }
    interface SsrShadowCmpAttributes {
        "selected": boolean;
    }
    interface WrapSsrShadowCmpAttributes {
        "selected": boolean;
    }

    interface IntrinsicElements {
        "another-car-detail": Omit<AnotherCarDetail, keyof AnotherCarDetailAttributes> & { [K in keyof AnotherCarDetail & keyof AnotherCarDetailAttributes]?: AnotherCarDetail[K] } & { [K in keyof AnotherCarDetail & keyof AnotherCarDetailAttributes as `attr:${K}`]?: AnotherCarDetailAttributes[K] } & { [K in keyof AnotherCarDetail & keyof AnotherCarDetailAttributes as `prop:${K}`]?: AnotherCarDetail[K] };
        "another-car-list": Omit<AnotherCarList, keyof AnotherCarListAttributes> & { [K in keyof AnotherCarList & keyof AnotherCarListAttributes]?: AnotherCarList[K] } & { [K in keyof AnotherCarList & keyof AnotherCarListAttributes as `attr:${K}`]?: AnotherCarListAttributes[K] } & { [K in keyof AnotherCarList & keyof AnotherCarListAttributes as `prop:${K}`]?: AnotherCarList[K] };
        "car-detail": Omit<CarDetail, keyof CarDetailAttributes> & { [K in keyof CarDetail & keyof CarDetailAttributes]?: CarDetail[K] } & { [K in keyof CarDetail & keyof CarDetailAttributes as `attr:${K}`]?: CarDetailAttributes[K] } & { [K in keyof CarDetail & keyof CarDetailAttributes as `prop:${K}`]?: CarDetail[K] };
        "car-list": Omit<CarList, keyof CarListAttributes> & { [K in keyof CarList & keyof CarListAttributes]?: CarList[K] } & { [K in keyof CarList & keyof CarListAttributes as `attr:${K}`]?: CarListAttributes[K] } & { [K in keyof CarList & keyof CarListAttributes as `prop:${K}`]?: CarList[K] };
        "cmp-dsd": Omit<CmpDsd, keyof CmpDsdAttributes> & { [K in keyof CmpDsd & keyof CmpDsdAttributes]?: CmpDsd[K] } & { [K in keyof CmpDsd & keyof CmpDsdAttributes as `attr:${K}`]?: CmpDsdAttributes[K] } & { [K in keyof CmpDsd & keyof CmpDsdAttributes as `prop:${K}`]?: CmpDsd[K] };
        "cmp-dsd-focus": CmpDsdFocus;
        "cmp-server-vs-client": CmpServerVsClient;
        "cmp-with-slot": CmpWithSlot;
        "complex-properties": Omit<ComplexProperties, keyof ComplexPropertiesAttributes> & { [K in keyof ComplexProperties & keyof ComplexPropertiesAttributes]?: ComplexProperties[K] } & { [K in keyof ComplexProperties & keyof ComplexPropertiesAttributes as `attr:${K}`]?: ComplexPropertiesAttributes[K] } & { [K in keyof ComplexProperties & keyof ComplexPropertiesAttributes as `prop:${K}`]?: ComplexProperties[K] };
        "dsd-listen-cmp": DsdListenCmp;
        "hydrated-sibling-accessors": HydratedSiblingAccessors;
        "my-cmp": Omit<MyCmp, keyof MyCmpAttributes> & { [K in keyof MyCmp & keyof MyCmpAttributes]?: MyCmp[K] } & { [K in keyof MyCmp & keyof MyCmpAttributes as `attr:${K}`]?: MyCmpAttributes[K] } & { [K in keyof MyCmp & keyof MyCmpAttributes as `prop:${K}`]?: MyCmp[K] };
        "my-jsx-cmp": Omit<MyJsxCmp, keyof MyJsxCmpAttributes> & { [K in keyof MyJsxCmp & keyof MyJsxCmpAttributes]?: MyJsxCmp[K] } & { [K in keyof MyJsxCmp & keyof MyJsxCmpAttributes as `attr:${K}`]?: MyJsxCmpAttributes[K] } & { [K in keyof MyJsxCmp & keyof MyJsxCmpAttributes as `prop:${K}`]?: MyJsxCmp[K] };
        "nested-cmp-child": NestedCmpChild;
        "nested-cmp-parent": NestedCmpParent;
        "nested-scope-cmp": NestedScopeCmp;
        "non-shadow-child": NonShadowChild;
        "non-shadow-forwarded-slot": NonShadowForwardedSlot;
        "non-shadow-multi-slots": NonShadowMultiSlots;
        "non-shadow-wrapper": NonShadowWrapper;
        "part-ssr-shadow-cmp": Omit<PartSsrShadowCmp, keyof PartSsrShadowCmpAttributes> & { [K in keyof PartSsrShadowCmp & keyof PartSsrShadowCmpAttributes]?: PartSsrShadowCmp[K] } & { [K in keyof PartSsrShadowCmp & keyof PartSsrShadowCmpAttributes as `attr:${K}`]?: PartSsrShadowCmpAttributes[K] } & { [K in keyof PartSsrShadowCmp & keyof PartSsrShadowCmpAttributes as `prop:${K}`]?: PartSsrShadowCmp[K] };
        "part-wrap-ssr-shadow-cmp": Omit<PartWrapSsrShadowCmp, keyof PartWrapSsrShadowCmpAttributes> & { [K in keyof PartWrapSsrShadowCmp & keyof PartWrapSsrShadowCmpAttributes]?: PartWrapSsrShadowCmp[K] } & { [K in keyof PartWrapSsrShadowCmp & keyof PartWrapSsrShadowCmpAttributes as `attr:${K}`]?: PartWrapSsrShadowCmpAttributes[K] } & { [K in keyof PartWrapSsrShadowCmp & keyof PartWrapSsrShadowCmpAttributes as `prop:${K}`]?: PartWrapSsrShadowCmp[K] };
        "prerender-cmp": PrerenderCmp;
        "prop-cmp": Omit<PropCmp, keyof PropCmpAttributes> & { [K in keyof PropCmp & keyof PropCmpAttributes]?: PropCmp[K] } & { [K in keyof PropCmp & keyof PropCmpAttributes as `attr:${K}`]?: PropCmpAttributes[K] } & { [K in keyof PropCmp & keyof PropCmpAttributes as `prop:${K}`]?: PropCmp[K] };
        "runtime-decorators": Omit<RuntimeDecorators, keyof RuntimeDecoratorsAttributes> & { [K in keyof RuntimeDecorators & keyof RuntimeDecoratorsAttributes]?: RuntimeDecorators[K] } & { [K in keyof RuntimeDecorators & keyof RuntimeDecoratorsAttributes as `attr:${K}`]?: RuntimeDecoratorsAttributes[K] } & { [K in keyof RuntimeDecorators & keyof RuntimeDecoratorsAttributes as `prop:${K}`]?: RuntimeDecorators[K] };
        "scoped-car-detail": Omit<ScopedCarDetail, keyof ScopedCarDetailAttributes> & { [K in keyof ScopedCarDetail & keyof ScopedCarDetailAttributes]?: ScopedCarDetail[K] } & { [K in keyof ScopedCarDetail & keyof ScopedCarDetailAttributes as `attr:${K}`]?: ScopedCarDetailAttributes[K] } & { [K in keyof ScopedCarDetail & keyof ScopedCarDetailAttributes as `prop:${K}`]?: ScopedCarDetail[K] };
        "scoped-car-list": Omit<ScopedCarList, keyof ScopedCarListAttributes> & { [K in keyof ScopedCarList & keyof ScopedCarListAttributes]?: ScopedCarList[K] } & { [K in keyof ScopedCarList & keyof ScopedCarListAttributes as `attr:${K}`]?: ScopedCarListAttributes[K] } & { [K in keyof ScopedCarList & keyof ScopedCarListAttributes as `prop:${K}`]?: ScopedCarList[K] };
        "scoped-ssr-child-cmp": ScopedSsrChildCmp;
        "scoped-ssr-parent-cmp": ScopedSsrParentCmp;
        "serialize-deserializer": Omit<SerializeDeserializer, keyof SerializeDeserializerAttributes> & { [K in keyof SerializeDeserializer & keyof SerializeDeserializerAttributes]?: SerializeDeserializer[K] } & { [K in keyof SerializeDeserializer & keyof SerializeDeserializerAttributes as `attr:${K}`]?: SerializeDeserializerAttributes[K] } & { [K in keyof SerializeDeserializer & keyof SerializeDeserializerAttributes as `prop:${K}`]?: SerializeDeserializer[K] };
        "shadow-child": ShadowChild;
        "shadow-ssr-child-cmp": ShadowSsrChildCmp;
        "shadow-ssr-parent-cmp": ShadowSsrParentCmp;
        "shadow-wrapper": ShadowWrapper;
        "slow-ssr-prop": SlowSsrProp;
        "ssr-order-cmp": SsrOrderCmp;
        "ssr-order-wrap-cmp": SsrOrderWrapCmp;
        "ssr-shadow-cmp": Omit<SsrShadowCmp, keyof SsrShadowCmpAttributes> & { [K in keyof SsrShadowCmp & keyof SsrShadowCmpAttributes]?: SsrShadowCmp[K] } & { [K in keyof SsrShadowCmp & keyof SsrShadowCmpAttributes as `attr:${K}`]?: SsrShadowCmpAttributes[K] } & { [K in keyof SsrShadowCmp & keyof SsrShadowCmpAttributes as `prop:${K}`]?: SsrShadowCmp[K] };
        "wrap-ssr-shadow-cmp": Omit<WrapSsrShadowCmp, keyof WrapSsrShadowCmpAttributes> & { [K in keyof WrapSsrShadowCmp & keyof WrapSsrShadowCmpAttributes]?: WrapSsrShadowCmp[K] } & { [K in keyof WrapSsrShadowCmp & keyof WrapSsrShadowCmpAttributes as `attr:${K}`]?: WrapSsrShadowCmpAttributes[K] } & { [K in keyof WrapSsrShadowCmp & keyof WrapSsrShadowCmpAttributes as `prop:${K}`]?: WrapSsrShadowCmp[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "another-car-detail": LocalJSX.IntrinsicElements["another-car-detail"] & JSXBase.HTMLAttributes<HTMLAnotherCarDetailElement>;
            /**
             * Component that helps display a list of cars
             */
            "another-car-list": LocalJSX.IntrinsicElements["another-car-list"] & JSXBase.HTMLAttributes<HTMLAnotherCarListElement>;
            "car-detail": LocalJSX.IntrinsicElements["car-detail"] & JSXBase.HTMLAttributes<HTMLCarDetailElement>;
            /**
             * Component that helps display a list of cars
             */
            "car-list": LocalJSX.IntrinsicElements["car-list"] & JSXBase.HTMLAttributes<HTMLCarListElement>;
            "cmp-dsd": LocalJSX.IntrinsicElements["cmp-dsd"] & JSXBase.HTMLAttributes<HTMLCmpDsdElement>;
            "cmp-dsd-focus": LocalJSX.IntrinsicElements["cmp-dsd-focus"] & JSXBase.HTMLAttributes<HTMLCmpDsdFocusElement>;
            "cmp-server-vs-client": LocalJSX.IntrinsicElements["cmp-server-vs-client"] & JSXBase.HTMLAttributes<HTMLCmpServerVsClientElement>;
            "cmp-with-slot": LocalJSX.IntrinsicElements["cmp-with-slot"] & JSXBase.HTMLAttributes<HTMLCmpWithSlotElement>;
            "complex-properties": LocalJSX.IntrinsicElements["complex-properties"] & JSXBase.HTMLAttributes<HTMLComplexPropertiesElement>;
            "dsd-listen-cmp": LocalJSX.IntrinsicElements["dsd-listen-cmp"] & JSXBase.HTMLAttributes<HTMLDsdListenCmpElement>;
            "hydrated-sibling-accessors": LocalJSX.IntrinsicElements["hydrated-sibling-accessors"] & JSXBase.HTMLAttributes<HTMLHydratedSiblingAccessorsElement>;
            "my-cmp": LocalJSX.IntrinsicElements["my-cmp"] & JSXBase.HTMLAttributes<HTMLMyCmpElement>;
            "my-jsx-cmp": LocalJSX.IntrinsicElements["my-jsx-cmp"] & JSXBase.HTMLAttributes<HTMLMyJsxCmpElement>;
            "nested-cmp-child": LocalJSX.IntrinsicElements["nested-cmp-child"] & JSXBase.HTMLAttributes<HTMLNestedCmpChildElement>;
            "nested-cmp-parent": LocalJSX.IntrinsicElements["nested-cmp-parent"] & JSXBase.HTMLAttributes<HTMLNestedCmpParentElement>;
            "nested-scope-cmp": LocalJSX.IntrinsicElements["nested-scope-cmp"] & JSXBase.HTMLAttributes<HTMLNestedScopeCmpElement>;
            "non-shadow-child": LocalJSX.IntrinsicElements["non-shadow-child"] & JSXBase.HTMLAttributes<HTMLNonShadowChildElement>;
            "non-shadow-forwarded-slot": LocalJSX.IntrinsicElements["non-shadow-forwarded-slot"] & JSXBase.HTMLAttributes<HTMLNonShadowForwardedSlotElement>;
            "non-shadow-multi-slots": LocalJSX.IntrinsicElements["non-shadow-multi-slots"] & JSXBase.HTMLAttributes<HTMLNonShadowMultiSlotsElement>;
            "non-shadow-wrapper": LocalJSX.IntrinsicElements["non-shadow-wrapper"] & JSXBase.HTMLAttributes<HTMLNonShadowWrapperElement>;
            "part-ssr-shadow-cmp": LocalJSX.IntrinsicElements["part-ssr-shadow-cmp"] & JSXBase.HTMLAttributes<HTMLPartSsrShadowCmpElement>;
            "part-wrap-ssr-shadow-cmp": LocalJSX.IntrinsicElements["part-wrap-ssr-shadow-cmp"] & JSXBase.HTMLAttributes<HTMLPartWrapSsrShadowCmpElement>;
            "prerender-cmp": LocalJSX.IntrinsicElements["prerender-cmp"] & JSXBase.HTMLAttributes<HTMLPrerenderCmpElement>;
            "prop-cmp": LocalJSX.IntrinsicElements["prop-cmp"] & JSXBase.HTMLAttributes<HTMLPropCmpElement>;
            "runtime-decorators": LocalJSX.IntrinsicElements["runtime-decorators"] & JSXBase.HTMLAttributes<HTMLRuntimeDecoratorsElement>;
            "scoped-car-detail": LocalJSX.IntrinsicElements["scoped-car-detail"] & JSXBase.HTMLAttributes<HTMLScopedCarDetailElement>;
            /**
             * Component that helps display a list of cars
             */
            "scoped-car-list": LocalJSX.IntrinsicElements["scoped-car-list"] & JSXBase.HTMLAttributes<HTMLScopedCarListElement>;
            "scoped-ssr-child-cmp": LocalJSX.IntrinsicElements["scoped-ssr-child-cmp"] & JSXBase.HTMLAttributes<HTMLScopedSsrChildCmpElement>;
            "scoped-ssr-parent-cmp": LocalJSX.IntrinsicElements["scoped-ssr-parent-cmp"] & JSXBase.HTMLAttributes<HTMLScopedSsrParentCmpElement>;
            "serialize-deserializer": LocalJSX.IntrinsicElements["serialize-deserializer"] & JSXBase.HTMLAttributes<HTMLSerializeDeserializerElement>;
            "shadow-child": LocalJSX.IntrinsicElements["shadow-child"] & JSXBase.HTMLAttributes<HTMLShadowChildElement>;
            "shadow-ssr-child-cmp": LocalJSX.IntrinsicElements["shadow-ssr-child-cmp"] & JSXBase.HTMLAttributes<HTMLShadowSsrChildCmpElement>;
            "shadow-ssr-parent-cmp": LocalJSX.IntrinsicElements["shadow-ssr-parent-cmp"] & JSXBase.HTMLAttributes<HTMLShadowSsrParentCmpElement>;
            "shadow-wrapper": LocalJSX.IntrinsicElements["shadow-wrapper"] & JSXBase.HTMLAttributes<HTMLShadowWrapperElement>;
            "slow-ssr-prop": LocalJSX.IntrinsicElements["slow-ssr-prop"] & JSXBase.HTMLAttributes<HTMLSlowSsrPropElement>;
            "ssr-order-cmp": LocalJSX.IntrinsicElements["ssr-order-cmp"] & JSXBase.HTMLAttributes<HTMLSsrOrderCmpElement>;
            "ssr-order-wrap-cmp": LocalJSX.IntrinsicElements["ssr-order-wrap-cmp"] & JSXBase.HTMLAttributes<HTMLSsrOrderWrapCmpElement>;
            "ssr-shadow-cmp": LocalJSX.IntrinsicElements["ssr-shadow-cmp"] & JSXBase.HTMLAttributes<HTMLSsrShadowCmpElement>;
            "wrap-ssr-shadow-cmp": LocalJSX.IntrinsicElements["wrap-ssr-shadow-cmp"] & JSXBase.HTMLAttributes<HTMLWrapSsrShadowCmpElement>;
        }
    }
}
