/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomElementsFormAssociated {
    }
}
declare global {
    interface HTMLCustomElementsFormAssociatedElement extends Components.CustomElementsFormAssociated, HTMLStencilElement {
    }
    var HTMLCustomElementsFormAssociatedElement: {
        prototype: HTMLCustomElementsFormAssociatedElement;
        new (): HTMLCustomElementsFormAssociatedElement;
    };
    interface HTMLElementTagNameMap {
        "custom-elements-form-associated": HTMLCustomElementsFormAssociatedElement;
    }
}
declare namespace LocalJSX {
    interface CustomElementsFormAssociated {
        /**
          * If `true`, the user cannot interact with the element.
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * The name of the element, used when submitting an HTML form.
         */
        "name"?: string;
    }


    interface IntrinsicElements {
        "custom-elements-form-associated": CustomElementsFormAssociated;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-elements-form-associated": LocalJSX.IntrinsicElements["custom-elements-form-associated"] & JSXBase.HTMLAttributes<HTMLCustomElementsFormAssociatedElement>;
        }
    }
}
