import type * as d from '@stencil/core';
import type { Plugin } from 'rolldown';

import { join } from '../../utils';
import { USER_INDEX_ENTRY_ID } from './entry-alias-ids';

export const userIndexPlugin = (config: d.ValidatedConfig, compilerCtx: d.CompilerCtx): Plugin => {
  return {
    name: 'userIndexPlugin',

    // Use Rolldown's hook filter to only process @user-index-entrypoint
    resolveId: {
      filter: { id: /^@user-index-entrypoint$/ },
      async handler(importee) {
        if (importee === USER_INDEX_ENTRY_ID) {
          const usersIndexJsPath = join(config.srcDir, 'index.ts');
          const hasUserIndex = await compilerCtx.fs.access(usersIndexJsPath);
          if (hasUserIndex) {
            return usersIndexJsPath;
          }
          return importee;
        }
        return null;
      },
    },

    load: {
      filter: { id: /^@user-index-entrypoint$/ },
      handler(id) {
        if (id === USER_INDEX_ENTRY_ID) {
          return `//! Autogenerated index`;
        }
        return null;
      },
    },
  };
};
