/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
export namespace Components {
    interface TestComponent {
        /**
          * The text to display
         */
        "t": string;
    }
}
declare global {
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "test-component": HTMLTestComponentElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface TestComponent {
        /**
          * The text to display
         */
        "t": string;
    }

    interface TestComponentAttributes {
        "t": string;
    }

    interface IntrinsicElements {
        "test-component": Omit<TestComponent, keyof TestComponentAttributes> & { [K in keyof TestComponent & keyof TestComponentAttributes]?: TestComponent[K] } & { [K in keyof TestComponent & keyof TestComponentAttributes as `attr:${K}`]?: TestComponentAttributes[K] } & { [K in keyof TestComponent & keyof TestComponentAttributes as `prop:${K}`]?: TestComponent[K] } & OneOf<"t", TestComponent["t"], TestComponentAttributes["t"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-component": LocalJSX.IntrinsicElements["test-component"] & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
        }
    }
}
