/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
export namespace Components {
    /**
     * A non-shadow component WITHOUT any patches enabled.
     * Used as a control to compare against patched components.
     */
    interface NoPatchComponent {
    }
    /**
     * A non-shadow component that uses `patches: ['all']` to enable
     * all slot-related DOM patching (childNodes, appendChild, cloneNode, etc.)
     */
    interface PatchAllComponent {
    }
    /**
     * A non-shadow component that uses `patches: ['children']` to enable
     * patching of child node accessors (childNodes, children, firstChild, lastChild).
     */
    interface PatchChildrenComponent {
    }
    /**
     * A non-shadow component that uses `patches: ['clone']` to enable
     * patching of cloneNode() to properly handle slotted content.
     */
    interface PatchCloneComponent {
    }
    /**
     * A non-shadow component that uses multiple patches combined:
     * `patches: ['children', 'clone', 'insert']`
     * This tests that individual patches can be combined without using 'all'.
     */
    interface PatchCombinedComponent {
    }
    /**
     * A non-shadow component that uses `patches: ['insert']` to enable
     * patching of appendChild(), insertBefore(), etc. for slot relocation.
     */
    interface PatchInsertComponent {
    }
}
declare global {
    /**
     * A non-shadow component WITHOUT any patches enabled.
     * Used as a control to compare against patched components.
     */
    interface HTMLNoPatchComponentElement extends Components.NoPatchComponent, HTMLStencilElement {
    }
    var HTMLNoPatchComponentElement: {
        prototype: HTMLNoPatchComponentElement;
        new (): HTMLNoPatchComponentElement;
    };
    /**
     * A non-shadow component that uses `patches: ['all']` to enable
     * all slot-related DOM patching (childNodes, appendChild, cloneNode, etc.)
     */
    interface HTMLPatchAllComponentElement extends Components.PatchAllComponent, HTMLStencilElement {
    }
    var HTMLPatchAllComponentElement: {
        prototype: HTMLPatchAllComponentElement;
        new (): HTMLPatchAllComponentElement;
    };
    /**
     * A non-shadow component that uses `patches: ['children']` to enable
     * patching of child node accessors (childNodes, children, firstChild, lastChild).
     */
    interface HTMLPatchChildrenComponentElement extends Components.PatchChildrenComponent, HTMLStencilElement {
    }
    var HTMLPatchChildrenComponentElement: {
        prototype: HTMLPatchChildrenComponentElement;
        new (): HTMLPatchChildrenComponentElement;
    };
    /**
     * A non-shadow component that uses `patches: ['clone']` to enable
     * patching of cloneNode() to properly handle slotted content.
     */
    interface HTMLPatchCloneComponentElement extends Components.PatchCloneComponent, HTMLStencilElement {
    }
    var HTMLPatchCloneComponentElement: {
        prototype: HTMLPatchCloneComponentElement;
        new (): HTMLPatchCloneComponentElement;
    };
    /**
     * A non-shadow component that uses multiple patches combined:
     * `patches: ['children', 'clone', 'insert']`
     * This tests that individual patches can be combined without using 'all'.
     */
    interface HTMLPatchCombinedComponentElement extends Components.PatchCombinedComponent, HTMLStencilElement {
    }
    var HTMLPatchCombinedComponentElement: {
        prototype: HTMLPatchCombinedComponentElement;
        new (): HTMLPatchCombinedComponentElement;
    };
    /**
     * A non-shadow component that uses `patches: ['insert']` to enable
     * patching of appendChild(), insertBefore(), etc. for slot relocation.
     */
    interface HTMLPatchInsertComponentElement extends Components.PatchInsertComponent, HTMLStencilElement {
    }
    var HTMLPatchInsertComponentElement: {
        prototype: HTMLPatchInsertComponentElement;
        new (): HTMLPatchInsertComponentElement;
    };
    interface HTMLElementTagNameMap {
        "no-patch-component": HTMLNoPatchComponentElement;
        "patch-all-component": HTMLPatchAllComponentElement;
        "patch-children-component": HTMLPatchChildrenComponentElement;
        "patch-clone-component": HTMLPatchCloneComponentElement;
        "patch-combined-component": HTMLPatchCombinedComponentElement;
        "patch-insert-component": HTMLPatchInsertComponentElement;
    }
}
declare namespace LocalJSX {
    /**
     * A non-shadow component WITHOUT any patches enabled.
     * Used as a control to compare against patched components.
     */
    interface NoPatchComponent {
    }
    /**
     * A non-shadow component that uses `patches: ['all']` to enable
     * all slot-related DOM patching (childNodes, appendChild, cloneNode, etc.)
     */
    interface PatchAllComponent {
    }
    /**
     * A non-shadow component that uses `patches: ['children']` to enable
     * patching of child node accessors (childNodes, children, firstChild, lastChild).
     */
    interface PatchChildrenComponent {
    }
    /**
     * A non-shadow component that uses `patches: ['clone']` to enable
     * patching of cloneNode() to properly handle slotted content.
     */
    interface PatchCloneComponent {
    }
    /**
     * A non-shadow component that uses multiple patches combined:
     * `patches: ['children', 'clone', 'insert']`
     * This tests that individual patches can be combined without using 'all'.
     */
    interface PatchCombinedComponent {
    }
    /**
     * A non-shadow component that uses `patches: ['insert']` to enable
     * patching of appendChild(), insertBefore(), etc. for slot relocation.
     */
    interface PatchInsertComponent {
    }
    interface IntrinsicElements {
        "no-patch-component": NoPatchComponent;
        "patch-all-component": PatchAllComponent;
        "patch-children-component": PatchChildrenComponent;
        "patch-clone-component": PatchCloneComponent;
        "patch-combined-component": PatchCombinedComponent;
        "patch-insert-component": PatchInsertComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A non-shadow component WITHOUT any patches enabled.
             * Used as a control to compare against patched components.
             */
            "no-patch-component": LocalJSX.IntrinsicElements["no-patch-component"] & JSXBase.HTMLAttributes<HTMLNoPatchComponentElement>;
            /**
             * A non-shadow component that uses `patches: ['all']` to enable
             * all slot-related DOM patching (childNodes, appendChild, cloneNode, etc.)
             */
            "patch-all-component": LocalJSX.IntrinsicElements["patch-all-component"] & JSXBase.HTMLAttributes<HTMLPatchAllComponentElement>;
            /**
             * A non-shadow component that uses `patches: ['children']` to enable
             * patching of child node accessors (childNodes, children, firstChild, lastChild).
             */
            "patch-children-component": LocalJSX.IntrinsicElements["patch-children-component"] & JSXBase.HTMLAttributes<HTMLPatchChildrenComponentElement>;
            /**
             * A non-shadow component that uses `patches: ['clone']` to enable
             * patching of cloneNode() to properly handle slotted content.
             */
            "patch-clone-component": LocalJSX.IntrinsicElements["patch-clone-component"] & JSXBase.HTMLAttributes<HTMLPatchCloneComponentElement>;
            /**
             * A non-shadow component that uses multiple patches combined:
             * `patches: ['children', 'clone', 'insert']`
             * This tests that individual patches can be combined without using 'all'.
             */
            "patch-combined-component": LocalJSX.IntrinsicElements["patch-combined-component"] & JSXBase.HTMLAttributes<HTMLPatchCombinedComponentElement>;
            /**
             * A non-shadow component that uses `patches: ['insert']` to enable
             * patching of appendChild(), insertBefore(), etc. for slot relocation.
             */
            "patch-insert-component": LocalJSX.IntrinsicElements["patch-insert-component"] & JSXBase.HTMLAttributes<HTMLPatchInsertComponentElement>;
        }
    }
}
