/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
import { SomeTypes } from "./components/attribute-complex/types.js";
export { SomeTypes } from "./components/attribute-complex/types.js";
export namespace Components {
    interface AsyncRerender {
    }
    interface AttributeBasic {
        /**
          * @default 'my-custom-attr'
         */
        "customAttr": string;
        /**
          * @default 'getter'
         */
        "getter": string;
        /**
          * @default 'multiWord'
         */
        "multiWord": string;
        /**
          * @default 'single'
         */
        "single": string;
    }
    interface AttributeBasicRoot {
    }
    interface AttributeBoolean {
        "boolState"?: boolean;
        "noreflect"?: boolean;
        "strState"?: string;
    }
    interface AttributeBooleanRoot {
        "toggleState": () => Promise<void>;
    }
    interface AttributeComplex {
        /**
          * @default true
         */
        "bool0": boolean;
        "bool1"?: boolean;
        "bool2"?: boolean;
        "getInstance": () => Promise<this>;
        /**
          * @default 1
         */
        "nu0": number;
        "nu1"?: number;
        "nu2"?: SomeTypes.Number;
        "obj": string;
        /**
          * @default 'hello'
         */
        "str0": string;
        "str1"?: string;
        "str2"?: SomeTypes.String;
    }
    interface AttributeDeserializer {
        "array": string[];
        "bool": boolean;
        "getArray": () => Promise<any>;
        "getBools": () => Promise<boolean[]>;
        "getGetSet": () => Promise<any[]>;
        "getJson": () => Promise<any>;
        /**
          * @default { moo: 'bar' }
         */
        "getSet": { [key: string]: string };
        "json": { foo: string };
    }
    interface EventBasic {
    }
    interface SlotBasic {
    }
    interface SlotBasicRoot {
    }
}
export interface EventBasicCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEventBasicElement;
}
declare global {
    interface HTMLAsyncRerenderElement extends Components.AsyncRerender, HTMLStencilElement {
    }
    var HTMLAsyncRerenderElement: {
        prototype: HTMLAsyncRerenderElement;
        new (): HTMLAsyncRerenderElement;
    };
    interface HTMLAttributeBasicElement extends Components.AttributeBasic, HTMLStencilElement {
    }
    var HTMLAttributeBasicElement: {
        prototype: HTMLAttributeBasicElement;
        new (): HTMLAttributeBasicElement;
    };
    interface HTMLAttributeBasicRootElement extends Components.AttributeBasicRoot, HTMLStencilElement {
    }
    var HTMLAttributeBasicRootElement: {
        prototype: HTMLAttributeBasicRootElement;
        new (): HTMLAttributeBasicRootElement;
    };
    interface HTMLAttributeBooleanElement extends Components.AttributeBoolean, HTMLStencilElement {
    }
    var HTMLAttributeBooleanElement: {
        prototype: HTMLAttributeBooleanElement;
        new (): HTMLAttributeBooleanElement;
    };
    interface HTMLAttributeBooleanRootElement extends Components.AttributeBooleanRoot, HTMLStencilElement {
    }
    var HTMLAttributeBooleanRootElement: {
        prototype: HTMLAttributeBooleanRootElement;
        new (): HTMLAttributeBooleanRootElement;
    };
    interface HTMLAttributeComplexElement extends Components.AttributeComplex, HTMLStencilElement {
    }
    var HTMLAttributeComplexElement: {
        prototype: HTMLAttributeComplexElement;
        new (): HTMLAttributeComplexElement;
    };
    interface HTMLAttributeDeserializerElement extends Components.AttributeDeserializer, HTMLStencilElement {
    }
    var HTMLAttributeDeserializerElement: {
        prototype: HTMLAttributeDeserializerElement;
        new (): HTMLAttributeDeserializerElement;
    };
    interface HTMLEventBasicElementEventMap {
        "testEvent": any;
    }
    interface HTMLEventBasicElement extends Components.EventBasic, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEventBasicElementEventMap>(type: K, listener: (this: HTMLEventBasicElement, ev: EventBasicCustomEvent<HTMLEventBasicElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEventBasicElementEventMap>(type: K, listener: (this: HTMLEventBasicElement, ev: EventBasicCustomEvent<HTMLEventBasicElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEventBasicElement: {
        prototype: HTMLEventBasicElement;
        new (): HTMLEventBasicElement;
    };
    interface HTMLSlotBasicElement extends Components.SlotBasic, HTMLStencilElement {
    }
    var HTMLSlotBasicElement: {
        prototype: HTMLSlotBasicElement;
        new (): HTMLSlotBasicElement;
    };
    interface HTMLSlotBasicRootElement extends Components.SlotBasicRoot, HTMLStencilElement {
    }
    var HTMLSlotBasicRootElement: {
        prototype: HTMLSlotBasicRootElement;
        new (): HTMLSlotBasicRootElement;
    };
    interface HTMLElementTagNameMap {
        "async-rerender": HTMLAsyncRerenderElement;
        "attribute-basic": HTMLAttributeBasicElement;
        "attribute-basic-root": HTMLAttributeBasicRootElement;
        "attribute-boolean": HTMLAttributeBooleanElement;
        "attribute-boolean-root": HTMLAttributeBooleanRootElement;
        "attribute-complex": HTMLAttributeComplexElement;
        "attribute-deserializer": HTMLAttributeDeserializerElement;
        "event-basic": HTMLEventBasicElement;
        "slot-basic": HTMLSlotBasicElement;
        "slot-basic-root": HTMLSlotBasicRootElement;
    }
}
declare namespace LocalJSX {
    interface AsyncRerender {
    }
    interface AttributeBasic {
        /**
          * @default 'my-custom-attr'
         */
        "customAttr"?: string;
        /**
          * @default 'getter'
         */
        "getter"?: string;
        /**
          * @default 'multiWord'
         */
        "multiWord"?: string;
        /**
          * @default 'single'
         */
        "single"?: string;
    }
    interface AttributeBasicRoot {
    }
    interface AttributeBoolean {
        "boolState"?: boolean;
        "noreflect"?: boolean;
        "strState"?: string;
    }
    interface AttributeBooleanRoot {
    }
    interface AttributeComplex {
        /**
          * @default true
         */
        "bool0"?: boolean;
        "bool1"?: boolean;
        "bool2"?: boolean;
        /**
          * @default 1
         */
        "nu0"?: number;
        "nu1"?: number;
        "nu2"?: SomeTypes.Number;
        "obj"?: string;
        /**
          * @default 'hello'
         */
        "str0"?: string;
        "str1"?: string;
        "str2"?: SomeTypes.String;
    }
    interface AttributeDeserializer {
        "array"?: string[];
        "bool"?: boolean;
        /**
          * @default { moo: 'bar' }
         */
        "getSet"?: { [key: string]: string };
        "json"?: { foo: string };
    }
    interface EventBasic {
        "onTestEvent"?: (event: EventBasicCustomEvent<any>) => void;
    }
    interface SlotBasic {
    }
    interface SlotBasicRoot {
    }

    interface AttributeBasicAttributes {
        "single": string;
        "multiWord": string;
        "customAttr": string;
        "getter": string;
    }
    interface AttributeBooleanAttributes {
        "boolState": boolean;
        "strState": string;
        "noreflect": boolean;
    }
    interface AttributeComplexAttributes {
        "nu0": number;
        "nu1": number;
        "nu2": SomeTypes.Number;
        "bool0": boolean;
        "bool1": boolean;
        "bool2": boolean;
        "str0": string;
        "str1": string;
        "str2": SomeTypes.String;
        "obj": string;
    }
    interface AttributeDeserializerAttributes {
        "bool": boolean;
        "array": string;
        "json": string;
        "getSet": string;
    }

    interface IntrinsicElements {
        "async-rerender": AsyncRerender;
        "attribute-basic": Omit<AttributeBasic, keyof AttributeBasicAttributes> & { [K in keyof AttributeBasic & keyof AttributeBasicAttributes]?: AttributeBasic[K] } & { [K in keyof AttributeBasic & keyof AttributeBasicAttributes as `attr:${K}`]?: AttributeBasicAttributes[K] } & { [K in keyof AttributeBasic & keyof AttributeBasicAttributes as `prop:${K}`]?: AttributeBasic[K] };
        "attribute-basic-root": AttributeBasicRoot;
        "attribute-boolean": Omit<AttributeBoolean, keyof AttributeBooleanAttributes> & { [K in keyof AttributeBoolean & keyof AttributeBooleanAttributes]?: AttributeBoolean[K] } & { [K in keyof AttributeBoolean & keyof AttributeBooleanAttributes as `attr:${K}`]?: AttributeBooleanAttributes[K] } & { [K in keyof AttributeBoolean & keyof AttributeBooleanAttributes as `prop:${K}`]?: AttributeBoolean[K] };
        "attribute-boolean-root": AttributeBooleanRoot;
        "attribute-complex": Omit<AttributeComplex, keyof AttributeComplexAttributes> & { [K in keyof AttributeComplex & keyof AttributeComplexAttributes]?: AttributeComplex[K] } & { [K in keyof AttributeComplex & keyof AttributeComplexAttributes as `attr:${K}`]?: AttributeComplexAttributes[K] } & { [K in keyof AttributeComplex & keyof AttributeComplexAttributes as `prop:${K}`]?: AttributeComplex[K] };
        "attribute-deserializer": Omit<AttributeDeserializer, keyof AttributeDeserializerAttributes> & { [K in keyof AttributeDeserializer & keyof AttributeDeserializerAttributes]?: AttributeDeserializer[K] } & { [K in keyof AttributeDeserializer & keyof AttributeDeserializerAttributes as `attr:${K}`]?: AttributeDeserializerAttributes[K] } & { [K in keyof AttributeDeserializer & keyof AttributeDeserializerAttributes as `prop:${K}`]?: AttributeDeserializer[K] };
        "event-basic": EventBasic;
        "slot-basic": SlotBasic;
        "slot-basic-root": SlotBasicRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "async-rerender": LocalJSX.IntrinsicElements["async-rerender"] & JSXBase.HTMLAttributes<HTMLAsyncRerenderElement>;
            "attribute-basic": LocalJSX.IntrinsicElements["attribute-basic"] & JSXBase.HTMLAttributes<HTMLAttributeBasicElement>;
            "attribute-basic-root": LocalJSX.IntrinsicElements["attribute-basic-root"] & JSXBase.HTMLAttributes<HTMLAttributeBasicRootElement>;
            "attribute-boolean": LocalJSX.IntrinsicElements["attribute-boolean"] & JSXBase.HTMLAttributes<HTMLAttributeBooleanElement>;
            "attribute-boolean-root": LocalJSX.IntrinsicElements["attribute-boolean-root"] & JSXBase.HTMLAttributes<HTMLAttributeBooleanRootElement>;
            "attribute-complex": LocalJSX.IntrinsicElements["attribute-complex"] & JSXBase.HTMLAttributes<HTMLAttributeComplexElement>;
            "attribute-deserializer": LocalJSX.IntrinsicElements["attribute-deserializer"] & JSXBase.HTMLAttributes<HTMLAttributeDeserializerElement>;
            "event-basic": LocalJSX.IntrinsicElements["event-basic"] & JSXBase.HTMLAttributes<HTMLEventBasicElement>;
            "slot-basic": LocalJSX.IntrinsicElements["slot-basic"] & JSXBase.HTMLAttributes<HTMLSlotBasicElement>;
            "slot-basic-root": LocalJSX.IntrinsicElements["slot-basic-root"] & JSXBase.HTMLAttributes<HTMLSlotBasicRootElement>;
        }
    }
}
