/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
export namespace Components {
    interface AsyncRerender {
    }
    interface AttributeBasic {
        /**
          * @default 'my-custom-attr'
         */
        "customAttr": string;
        /**
          * @default 'getter'
         */
        "getter": string;
        /**
          * @default 'multiWord'
         */
        "multiWord": string;
        /**
          * @default 'single'
         */
        "single": string;
    }
    interface AttributeBasicRoot {
    }
    interface EventBasic {
    }
    interface SlotBasic {
    }
    interface SlotBasicRoot {
    }
}
export interface EventBasicCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEventBasicElement;
}
declare global {
    interface HTMLAsyncRerenderElement extends Components.AsyncRerender, HTMLStencilElement {
    }
    var HTMLAsyncRerenderElement: {
        prototype: HTMLAsyncRerenderElement;
        new (): HTMLAsyncRerenderElement;
    };
    interface HTMLAttributeBasicElement extends Components.AttributeBasic, HTMLStencilElement {
    }
    var HTMLAttributeBasicElement: {
        prototype: HTMLAttributeBasicElement;
        new (): HTMLAttributeBasicElement;
    };
    interface HTMLAttributeBasicRootElement extends Components.AttributeBasicRoot, HTMLStencilElement {
    }
    var HTMLAttributeBasicRootElement: {
        prototype: HTMLAttributeBasicRootElement;
        new (): HTMLAttributeBasicRootElement;
    };
    interface HTMLEventBasicElementEventMap {
        "testEvent": any;
    }
    interface HTMLEventBasicElement extends Components.EventBasic, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEventBasicElementEventMap>(type: K, listener: (this: HTMLEventBasicElement, ev: EventBasicCustomEvent<HTMLEventBasicElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEventBasicElementEventMap>(type: K, listener: (this: HTMLEventBasicElement, ev: EventBasicCustomEvent<HTMLEventBasicElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEventBasicElement: {
        prototype: HTMLEventBasicElement;
        new (): HTMLEventBasicElement;
    };
    interface HTMLSlotBasicElement extends Components.SlotBasic, HTMLStencilElement {
    }
    var HTMLSlotBasicElement: {
        prototype: HTMLSlotBasicElement;
        new (): HTMLSlotBasicElement;
    };
    interface HTMLSlotBasicRootElement extends Components.SlotBasicRoot, HTMLStencilElement {
    }
    var HTMLSlotBasicRootElement: {
        prototype: HTMLSlotBasicRootElement;
        new (): HTMLSlotBasicRootElement;
    };
    interface HTMLElementTagNameMap {
        "async-rerender": HTMLAsyncRerenderElement;
        "attribute-basic": HTMLAttributeBasicElement;
        "attribute-basic-root": HTMLAttributeBasicRootElement;
        "event-basic": HTMLEventBasicElement;
        "slot-basic": HTMLSlotBasicElement;
        "slot-basic-root": HTMLSlotBasicRootElement;
    }
}
declare namespace LocalJSX {
    interface AsyncRerender {
    }
    interface AttributeBasic {
        /**
          * @default 'my-custom-attr'
         */
        "customAttr"?: string;
        /**
          * @default 'getter'
         */
        "getter"?: string;
        /**
          * @default 'multiWord'
         */
        "multiWord"?: string;
        /**
          * @default 'single'
         */
        "single"?: string;
    }
    interface AttributeBasicRoot {
    }
    interface EventBasic {
        "onTestEvent"?: (event: EventBasicCustomEvent<any>) => void;
    }
    interface SlotBasic {
    }
    interface SlotBasicRoot {
    }

    interface AttributeBasicAttributes {
        "single": string;
        "multiWord": string;
        "customAttr": string;
        "getter": string;
    }

    interface IntrinsicElements {
        "async-rerender": AsyncRerender;
        "attribute-basic": Omit<AttributeBasic, keyof AttributeBasicAttributes> & { [K in keyof AttributeBasic & keyof AttributeBasicAttributes]?: AttributeBasic[K] } & { [K in keyof AttributeBasic & keyof AttributeBasicAttributes as `attr:${K}`]?: AttributeBasicAttributes[K] } & { [K in keyof AttributeBasic & keyof AttributeBasicAttributes as `prop:${K}`]?: AttributeBasic[K] };
        "attribute-basic-root": AttributeBasicRoot;
        "event-basic": EventBasic;
        "slot-basic": SlotBasic;
        "slot-basic-root": SlotBasicRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "async-rerender": LocalJSX.IntrinsicElements["async-rerender"] & JSXBase.HTMLAttributes<HTMLAsyncRerenderElement>;
            "attribute-basic": LocalJSX.IntrinsicElements["attribute-basic"] & JSXBase.HTMLAttributes<HTMLAttributeBasicElement>;
            "attribute-basic-root": LocalJSX.IntrinsicElements["attribute-basic-root"] & JSXBase.HTMLAttributes<HTMLAttributeBasicRootElement>;
            "event-basic": LocalJSX.IntrinsicElements["event-basic"] & JSXBase.HTMLAttributes<HTMLEventBasicElement>;
            "slot-basic": LocalJSX.IntrinsicElements["slot-basic"] & JSXBase.HTMLAttributes<HTMLSlotBasicElement>;
            "slot-basic-root": LocalJSX.IntrinsicElements["slot-basic-root"] & JSXBase.HTMLAttributes<HTMLSlotBasicRootElement>;
        }
    }
}
