/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExtendedCmp {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface ExtendedCmpCmp {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface ExtendsAbstract {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'default text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface ExtendsCmpCmp {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'default text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface ExtendsExternal {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'default text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface ExtendsLocal {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'default text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface ExtendsMixinCmp {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        "method3": () => Promise<void>;
        /**
          * @default 'default text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
        /**
          * @default 'mixin b text'
         */
        "prop3": string;
    }
    interface TsTargetProps {
        /**
          * @default 'basicProp'
         */
        "basicProp": string;
        "decoratedGetterSetterProp": number;
        /**
          * @default -10
         */
        "decoratedProp": number;
        "dynamicLifecycle": string[];
    }
}
export interface ExtendsLocalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLExtendsLocalElement;
}
declare global {
    interface HTMLExtendedCmpElement extends Components.ExtendedCmp, HTMLStencilElement {
    }
    var HTMLExtendedCmpElement: {
        prototype: HTMLExtendedCmpElement;
        new (): HTMLExtendedCmpElement;
    };
    interface HTMLExtendedCmpCmpElement extends Components.ExtendedCmpCmp, HTMLStencilElement {
    }
    var HTMLExtendedCmpCmpElement: {
        prototype: HTMLExtendedCmpCmpElement;
        new (): HTMLExtendedCmpCmpElement;
    };
    interface HTMLExtendsAbstractElement extends Components.ExtendsAbstract, HTMLStencilElement {
    }
    var HTMLExtendsAbstractElement: {
        prototype: HTMLExtendsAbstractElement;
        new (): HTMLExtendsAbstractElement;
    };
    interface HTMLExtendsCmpCmpElement extends Components.ExtendsCmpCmp, HTMLStencilElement {
    }
    var HTMLExtendsCmpCmpElement: {
        prototype: HTMLExtendsCmpCmpElement;
        new (): HTMLExtendsCmpCmpElement;
    };
    interface HTMLExtendsExternalElement extends Components.ExtendsExternal, HTMLStencilElement {
    }
    var HTMLExtendsExternalElement: {
        prototype: HTMLExtendsExternalElement;
        new (): HTMLExtendsExternalElement;
    };
    interface HTMLExtendsLocalElementEventMap {
        "myEvent": string;
    }
    interface HTMLExtendsLocalElement extends Components.ExtendsLocal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLExtendsLocalElementEventMap>(type: K, listener: (this: HTMLExtendsLocalElement, ev: ExtendsLocalCustomEvent<HTMLExtendsLocalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLExtendsLocalElementEventMap>(type: K, listener: (this: HTMLExtendsLocalElement, ev: ExtendsLocalCustomEvent<HTMLExtendsLocalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLExtendsLocalElement: {
        prototype: HTMLExtendsLocalElement;
        new (): HTMLExtendsLocalElement;
    };
    interface HTMLExtendsMixinCmpElement extends Components.ExtendsMixinCmp, HTMLStencilElement {
    }
    var HTMLExtendsMixinCmpElement: {
        prototype: HTMLExtendsMixinCmpElement;
        new (): HTMLExtendsMixinCmpElement;
    };
    interface HTMLTsTargetPropsElement extends Components.TsTargetProps, HTMLStencilElement {
    }
    var HTMLTsTargetPropsElement: {
        prototype: HTMLTsTargetPropsElement;
        new (): HTMLTsTargetPropsElement;
    };
    interface HTMLElementTagNameMap {
        "extended-cmp": HTMLExtendedCmpElement;
        "extended-cmp-cmp": HTMLExtendedCmpCmpElement;
        "extends-abstract": HTMLExtendsAbstractElement;
        "extends-cmp-cmp": HTMLExtendsCmpCmpElement;
        "extends-external": HTMLExtendsExternalElement;
        "extends-local": HTMLExtendsLocalElement;
        "extends-mixin-cmp": HTMLExtendsMixinCmpElement;
        "ts-target-props": HTMLTsTargetPropsElement;
    }
}
declare namespace LocalJSX {
    interface ExtendedCmp {
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface ExtendedCmpCmp {
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface ExtendsAbstract {
        /**
          * @default 'default text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface ExtendsCmpCmp {
        /**
          * @default 'default text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface ExtendsExternal {
        /**
          * @default 'default text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface ExtendsLocal {
        "onMyEvent"?: (event: ExtendsLocalCustomEvent<string>) => void;
        /**
          * @default 'default text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface ExtendsMixinCmp {
        /**
          * @default 'default text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
        /**
          * @default 'mixin b text'
         */
        "prop3"?: string;
    }
    interface TsTargetProps {
        /**
          * @default 'basicProp'
         */
        "basicProp"?: string;
        "decoratedGetterSetterProp"?: number;
        /**
          * @default -10
         */
        "decoratedProp"?: number;
        "dynamicLifecycle"?: string[];
    }
    interface IntrinsicElements {
        "extended-cmp": ExtendedCmp;
        "extended-cmp-cmp": ExtendedCmpCmp;
        "extends-abstract": ExtendsAbstract;
        "extends-cmp-cmp": ExtendsCmpCmp;
        "extends-external": ExtendsExternal;
        "extends-local": ExtendsLocal;
        "extends-mixin-cmp": ExtendsMixinCmp;
        "ts-target-props": TsTargetProps;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "extended-cmp": LocalJSX.ExtendedCmp & JSXBase.HTMLAttributes<HTMLExtendedCmpElement>;
            "extended-cmp-cmp": LocalJSX.ExtendedCmpCmp & JSXBase.HTMLAttributes<HTMLExtendedCmpCmpElement>;
            "extends-abstract": LocalJSX.ExtendsAbstract & JSXBase.HTMLAttributes<HTMLExtendsAbstractElement>;
            "extends-cmp-cmp": LocalJSX.ExtendsCmpCmp & JSXBase.HTMLAttributes<HTMLExtendsCmpCmpElement>;
            "extends-external": LocalJSX.ExtendsExternal & JSXBase.HTMLAttributes<HTMLExtendsExternalElement>;
            "extends-local": LocalJSX.ExtendsLocal & JSXBase.HTMLAttributes<HTMLExtendsLocalElement>;
            "extends-mixin-cmp": LocalJSX.ExtendsMixinCmp & JSXBase.HTMLAttributes<HTMLExtendsMixinCmpElement>;
            "ts-target-props": LocalJSX.TsTargetProps & JSXBase.HTMLAttributes<HTMLTsTargetPropsElement>;
        }
    }
}
