/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface AutoLoaderChild {
    }
    interface AutoLoaderDynamic {
    }
    interface AutoLoaderRoot {
    }
}
declare global {
    interface HTMLAutoLoaderChildElement extends Components.AutoLoaderChild, HTMLStencilElement {
    }
    var HTMLAutoLoaderChildElement: {
        prototype: HTMLAutoLoaderChildElement;
        new (): HTMLAutoLoaderChildElement;
    };
    interface HTMLAutoLoaderDynamicElement extends Components.AutoLoaderDynamic, HTMLStencilElement {
    }
    var HTMLAutoLoaderDynamicElement: {
        prototype: HTMLAutoLoaderDynamicElement;
        new (): HTMLAutoLoaderDynamicElement;
    };
    interface HTMLAutoLoaderRootElement extends Components.AutoLoaderRoot, HTMLStencilElement {
    }
    var HTMLAutoLoaderRootElement: {
        prototype: HTMLAutoLoaderRootElement;
        new (): HTMLAutoLoaderRootElement;
    };
    interface HTMLElementTagNameMap {
        "auto-loader-child": HTMLAutoLoaderChildElement;
        "auto-loader-dynamic": HTMLAutoLoaderDynamicElement;
        "auto-loader-root": HTMLAutoLoaderRootElement;
    }
}
declare namespace LocalJSX {
    interface AutoLoaderChild {
    }
    interface AutoLoaderDynamic {
    }
    interface AutoLoaderRoot {
    }
    interface IntrinsicElements {
        "auto-loader-child": AutoLoaderChild;
        "auto-loader-dynamic": AutoLoaderDynamic;
        "auto-loader-root": AutoLoaderRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "auto-loader-child": LocalJSX.IntrinsicElements["auto-loader-child"] & JSXBase.HTMLAttributes<HTMLAutoLoaderChildElement>;
            "auto-loader-dynamic": LocalJSX.IntrinsicElements["auto-loader-dynamic"] & JSXBase.HTMLAttributes<HTMLAutoLoaderDynamicElement>;
            "auto-loader-root": LocalJSX.IntrinsicElements["auto-loader-root"] & JSXBase.HTMLAttributes<HTMLAutoLoaderRootElement>;
        }
    }
}
