/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
export namespace Components {
    interface FormAssociatedExternal {
    }
    interface NonShadow {
    }
}
declare global {
    interface HTMLFormAssociatedExternalElement extends Components.FormAssociatedExternal, HTMLStencilElement {
    }
    var HTMLFormAssociatedExternalElement: {
        prototype: HTMLFormAssociatedExternalElement;
        new (): HTMLFormAssociatedExternalElement;
    };
    interface HTMLNonShadowElement extends Components.NonShadow, HTMLStencilElement {
    }
    var HTMLNonShadowElement: {
        prototype: HTMLNonShadowElement;
        new (): HTMLNonShadowElement;
    };
    interface HTMLElementTagNameMap {
        "form-associated-external": HTMLFormAssociatedExternalElement;
        "non-shadow": HTMLNonShadowElement;
    }
}
declare namespace LocalJSX {
    interface FormAssociatedExternal {
        /**
          * If `true`, the user cannot interact with the element.
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * The name of the element, used when submitting an HTML form.
         */
        "name"?: string;
    }
    interface NonShadow {
    }
    interface IntrinsicElements {
        "form-associated-external": FormAssociatedExternal;
        "non-shadow": NonShadow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "form-associated-external": LocalJSX.IntrinsicElements["form-associated-external"] & JSXBase.HTMLAttributes<HTMLFormAssociatedExternalElement>;
            "non-shadow": LocalJSX.IntrinsicElements["non-shadow"] & JSXBase.HTMLAttributes<HTMLNonShadowElement>;
        }
    }
}
