import type * as d from '@stencil/core';

import {
  ASSETS,
  buildError,
  buildWarn,
  DIST_LAZY,
  GLOBAL_STYLE,
  isOutputTargetAssets,
  isOutputTargetGlobalStyle,
  isOutputTargetCollection,
  isOutputTargetTypes,
  isString,
  isValidConfigOutputTarget,
  STENCIL_REBUNDLE,
  TYPES,
  VALID_CONFIG_OUTPUT_TARGETS,
} from '../../../utils';

/**
 * Internal output target types that are programmatically generated by validators.
 * These should NOT be reprocessed if validation is called multiple times.
 */
const INTERNAL_OUTPUT_TARGETS = [DIST_LAZY] as const;
import { validateAssets } from './validate-assets';
import { validateCollection } from './validate-collection';
import { validateCustomOutput } from './validate-custom-output';
import { validateDocs } from './validate-docs';
import { validateGlobalStyle } from './validate-global-style';
import { validateLazy } from './validate-lazy';
import { validateLoaderBundle } from './validate-loader-bundle';
import { validateSsr } from './validate-ssr';
import { validateSsrWasm } from './validate-ssr-wasm';
import { validateStandalone } from './validate-standalone';
import { validateStats } from './validate-stats';
import { validateTypes } from './validate-types';
import { validateWww } from './validate-www';

export const validateOutputTargets = (config: d.ValidatedConfig, diagnostics: d.Diagnostic[]) => {
  // Filter out internal output targets that may have been added in a previous validation pass.
  // This handles the case where validateConfig is called multiple times on the same config object.
  const userOutputs = (config.outputTargets || [])
    .filter(
      (o) => !INTERNAL_OUTPUT_TARGETS.includes(o.type as (typeof INTERNAL_OUTPUT_TARGETS)[number]),
    )
    .slice();

  userOutputs.forEach((outputTarget) => {
    if (!isValidConfigOutputTarget(outputTarget.type)) {
      const err = buildError(diagnostics);
      err.messageText = `Invalid outputTarget type "${
        outputTarget.type
      }". Valid outputTarget types include: ${VALID_CONFIG_OUTPUT_TARGETS.map((t) => `"${t}"`).join(', ')}`;
    }
  });

  // Auto-generate types and collection in production builds unless explicitly configured
  autoGenerateOutputs(config, userOutputs, diagnostics);

  config.outputTargets = [
    ...validateTypes(config, userOutputs),
    ...validateCollection(config, userOutputs),
    ...validateGlobalStyle(config, userOutputs),
    ...validateAssets(config, userOutputs),
    ...validateStandalone(config, userOutputs),
    ...validateCustomOutput(config, diagnostics, userOutputs),
    ...validateLazy(config, userOutputs),
    ...validateWww(config, diagnostics, userOutputs),
    ...validateLoaderBundle(config, diagnostics, userOutputs),
    ...validateDocs(config, diagnostics, userOutputs),
    ...validateStats(config, userOutputs),
    ...validateSsrWasm(config, userOutputs),
  ];

  // SSR also gets info from the www output
  config.outputTargets = [
    ...config.outputTargets,
    ...validateSsr(config, [...userOutputs, ...config.outputTargets]),
  ];
};

/**
 * Auto-generate output targets unless explicitly configured.
 *
 * Output targets that are auto-generated by default to ensure parity between all distribution strategies:
 * - `types` and `collection`: auto-generated in production builds
 * - `global-style`: auto-generated when `globalStyle` is configured AND no explicit outputs with `input` (dev and prod)
 * - `assets`: always auto-generated (dev and prod) - the actual copy is a no-op if no assetsDirs
 *
 * @param config The Stencil configuration object
 * @param userOutputs The array of user-defined output targets to validate and potentially augment
 * @param diagnostics The diagnostics array for warnings/errors
 */
const autoGenerateOutputs = (
  config: d.ValidatedConfig,
  userOutputs: d.OutputTarget[],
  diagnostics: d.Diagnostic[],
) => {
  const hasExplicitTypes = userOutputs.some(isOutputTargetTypes);
  const hasExplicitCollection = userOutputs.some(isOutputTargetCollection);
  const hasExplicitAssets = userOutputs.some(isOutputTargetAssets);

  // Check for explicit global-style outputs
  const explicitGlobalStyles = userOutputs.filter(isOutputTargetGlobalStyle);
  const hasExplicitGlobalStyleWithInput = explicitGlobalStyles.some((o) =>
    isString((o as d.OutputTargetGlobalStyle).input),
  );

  // Warn if both globalStyle config AND explicit global-style with input are used
  if (config.globalStyle && hasExplicitGlobalStyleWithInput) {
    const warn = buildWarn(diagnostics);
    warn.messageText =
      `Both "globalStyle" config and explicit "global-style" output target with "input" are configured. ` +
      `Choose one approach. The explicit output target's "input" will be used; "globalStyle" config will be ignored ` +
      `for those outputs.`;
  }

  // Auto-generate global-style output if:
  // - globalStyle is configured in config
  // - AND no explicit global-style outputs exist (user hasn't taken control)
  // This runs in both dev and prod since global styles are needed for development
  if (config.globalStyle && explicitGlobalStyles.length === 0) {
    userOutputs.push({
      type: GLOBAL_STYLE,
    } as d.OutputTargetGlobalStyle);
  }

  // Auto-generate assets output if not explicitly configured
  // This runs in both dev and prod - the actual copy is a no-op if no components have assetsDirs
  if (!hasExplicitAssets) {
    userOutputs.push({
      type: ASSETS,
    } as d.OutputTargetAssets);
  }

  // Skip types and collection auto-generation in dev mode
  if (config.devMode) {
    return;
  }

  // Auto-generate types output if not explicitly configured
  if (!hasExplicitTypes) {
    userOutputs.push({
      type: TYPES,
    } as d.OutputTargetTypes);
  }

  // Auto-generate collection output if not explicitly configured
  if (!hasExplicitCollection) {
    userOutputs.push({
      type: STENCIL_REBUNDLE,
    } as d.OutputTargetCollection);
  }
};
