import type * as d from '@stencil/core';

import {
  buildError,
  isOutputTargetStencilRebundle,
  isOutputTargetTypes,
  isValidConfigOutputTarget,
  STENCIL_REBUNDLE,
  TYPES,
  VALID_CONFIG_OUTPUT_TARGETS,
} from '../../../utils';
import { validateCustomOutput } from './validate-custom-output';
import { validateDocs } from './validate-docs';
import { validateLazy } from './validate-lazy';
import { validateLoaderBundle } from './validate-loader-bundle';
import { validateSsr } from './validate-ssr';
import { validateStandalone } from './validate-standalone';
import { validateStats } from './validate-stats';
import { validateStencilRebundle } from './validate-stencil-rebundle';
import { validateTypes } from './validate-types';
import { validateWww } from './validate-www';

export const validateOutputTargets = (config: d.ValidatedConfig, diagnostics: d.Diagnostic[]) => {
  const userOutputs = (config.outputTargets || []).slice();

  userOutputs.forEach((outputTarget) => {
    if (!isValidConfigOutputTarget(outputTarget.type)) {
      const err = buildError(diagnostics);
      err.messageText = `Invalid outputTarget type "${
        outputTarget.type
      }". Valid outputTarget types include: ${VALID_CONFIG_OUTPUT_TARGETS.map((t) => `"${t}"`).join(', ')}`;
    }
  });

  // Auto-generate types and stencil-rebundle in production builds unless explicitly configured
  autoGenerateOutputs(config, userOutputs);

  config.outputTargets = [
    ...validateTypes(config, userOutputs),
    ...validateStencilRebundle(config, userOutputs),
    ...validateStandalone(config, userOutputs),
    ...validateCustomOutput(config, diagnostics, userOutputs),
    ...validateLazy(config, userOutputs),
    ...validateWww(config, diagnostics, userOutputs),
    ...validateLoaderBundle(config, userOutputs),
    ...validateDocs(config, diagnostics, userOutputs),
    ...validateStats(config, userOutputs),
  ];

  // SSR also gets info from the www output
  config.outputTargets = [
    ...config.outputTargets,
    ...validateSsr(config, [...userOutputs, ...config.outputTargets]),
  ];
};

/**
 * Auto-generate types and stencil-rebundle output targets in production builds
 * unless the user has explicitly configured them.
 *
 * In v5, types and stencil-rebundle are first-class output targets that are
 * auto-generated by default to ensure parity between all distribution strategies.
 * @param config The Stencil configuration object
 * @param userOutputs The array of user-defined output targets to validate and potentially augment
 */
const autoGenerateOutputs = (config: d.ValidatedConfig, userOutputs: d.OutputTarget[]) => {
  // Skip auto-generation in dev mode
  if (config.devMode) {
    return;
  }

  const hasExplicitTypes = userOutputs.some(isOutputTargetTypes);
  const hasExplicitStencilRebundle = userOutputs.some(isOutputTargetStencilRebundle);

  // Auto-generate types output if not explicitly configured
  if (!hasExplicitTypes) {
    userOutputs.push({
      type: TYPES,
    } as d.OutputTargetTypes);
  }

  // Auto-generate stencil-rebundle output if not explicitly configured
  if (!hasExplicitStencilRebundle) {
    userOutputs.push({
      type: STENCIL_REBUNDLE,
    } as d.OutputTargetStencilRebundle);
  }
};
