import type * as d from '@stencil/core';

import {
  buildError,
  isOutputTargetStencilMeta,
  isOutputTargetTypes,
  isValidConfigOutputTarget,
  STENCIL_META,
  TYPES,
  VALID_CONFIG_OUTPUT_TARGETS,
} from '../../../utils';
import { validateStencilMeta } from './validate-stencil-meta';
import { validateStandalone } from './validate-standalone';
import { validateCustomOutput } from './validate-custom-output';
import { validateLoaderBundle } from './validate-loader-bundle';
import { validateDocs } from './validate-docs';
import { validateSsr } from './validate-ssr';
import { validateLazy } from './validate-lazy';
import { validateStats } from './validate-stats';
import { validateTypes } from './validate-types';
import { validateWww } from './validate-www';

export const validateOutputTargets = (config: d.ValidatedConfig, diagnostics: d.Diagnostic[]) => {
  const userOutputs = (config.outputTargets || []).slice();

  userOutputs.forEach((outputTarget) => {
    if (!isValidConfigOutputTarget(outputTarget.type)) {
      const err = buildError(diagnostics);
      err.messageText = `Invalid outputTarget type "${
        outputTarget.type
      }". Valid outputTarget types include: ${VALID_CONFIG_OUTPUT_TARGETS.map((t) => `"${t}"`).join(', ')}`;
    }
  });

  // Auto-generate types and stencil-meta in production builds unless explicitly configured
  autoGenerateOutputs(config, userOutputs);

  config.outputTargets = [
    ...validateTypes(config, userOutputs),
    ...validateStencilMeta(config, userOutputs),
    ...validateStandalone(config, userOutputs),
    ...validateCustomOutput(config, diagnostics, userOutputs),
    ...validateLazy(config, userOutputs),
    ...validateWww(config, diagnostics, userOutputs),
    ...validateLoaderBundle(config, userOutputs),
    ...validateDocs(config, diagnostics, userOutputs),
    ...validateStats(config, userOutputs),
  ];

  // SSR also gets info from the www output
  config.outputTargets = [
    ...config.outputTargets,
    ...validateSsr(config, [...userOutputs, ...config.outputTargets]),
  ];
};

/**
 * Auto-generate types and stencil-meta output targets in production builds
 * unless the user has explicitly configured them.
 *
 * In v5, types and stencil-meta are first-class output targets that are
 * auto-generated by default to ensure parity between all distribution strategies.
 */
const autoGenerateOutputs = (config: d.ValidatedConfig, userOutputs: d.OutputTarget[]) => {
  // Skip auto-generation in dev mode
  if (config.devMode) {
    return;
  }

  const hasExplicitTypes = userOutputs.some(isOutputTargetTypes);
  const hasExplicitStencilMeta = userOutputs.some(isOutputTargetStencilMeta);

  // Auto-generate types output if not explicitly configured
  if (!hasExplicitTypes) {
    userOutputs.push({
      type: TYPES,
    } as d.OutputTargetTypes);
  }

  // Auto-generate stencil-meta output if not explicitly configured
  if (!hasExplicitStencilMeta) {
    userOutputs.push({
      type: STENCIL_META,
    } as d.OutputTargetStencilMeta);
  }
};
