name: Integration Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test_integration:
    name: Integration (${{ matrix.os }}, node ${{ matrix.node }})
    strategy:
      fail-fast: false
      matrix:
        node: ['22', '24']
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: stencil-build
          path: packages/

      - name: Install Playwright Browsers
        uses: ./.github/workflows/actions/install-playwright

      - name: Integration Tests
        run: pnpm --filter "@stencil-core-tests/integration" test
        shell: bash

      - name: Build Unplugin
        run: pnpm --filter "@stencil/unplugin" build
        shell: bash

      - name: Unplugin Browser Tests
        run: pnpm --filter "@stencil/unplugin" test:browser
        shell: bash
