name: Component Starter Smoke Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  component_starter:
    name: Component Starter (${{ matrix.os }}, node ${{ matrix.node }})
    strategy:
      fail-fast: false
      matrix:
        node: ['22', '24']
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: stencil-build
          path: packages/

      - name: Pack @stencil/core
        run: pnpm pack --pack-destination ../../
        working-directory: ./packages/core
        shell: bash

      - name: Pack @stencil/cli
        run: pnpm pack --pack-destination ../../
        working-directory: ./packages/cli
        shell: bash

      - name: Initialize Component Starter
        run: npm init stencil component tmp-component-starter
        shell: bash

      - name: Install Component Starter Dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./tmp-component-starter
        shell: bash

      - name: Install Stencil from Pack
        run: npm install ../stencil-cli-*.tgz ../stencil-core-*.tgz --legacy-peer-deps
        working-directory: ./tmp-component-starter
        shell: bash

      - name: Install Playwright Browsers
        uses: ./.github/workflows/actions/install-playwright

      - name: Run Stencil Migrations
        run: npx stencil migrate
        working-directory: ./tmp-component-starter
        shell: bash

      - name: Build Starter Project
        run: npm run build
        working-directory: ./tmp-component-starter
        shell: bash

      - name: Test Starter Project
        run: npm run test -- --no-build
        working-directory: ./tmp-component-starter
        shell: bash
