name: 'Get Core Dependencies'
description: 'Sets up pnpm, node version & installs dependencies'
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node Version from Volta
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: './package.json'
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      shell: bash
