name: 'Get Core Dependencies'
description: 'sets the node version & initializes core dependencies'
runs:
  using: composite
  steps:
    # this overrides previous versions of the node runtime that was set.
    # jobs that need a different version of the Node runtime should explicitly
    # set their node version after running this step
    - name: 🟢 Use Node Version from Volta
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: './package.json'
        cache: 'npm'

    - name: 🕸️ Install Dependencies
      run: |
        npm ci \
        && npm run install.jest

      shell: bash
